siteorigin/so-widgets-bundle

widgets/so-slider-widget/tpl/base.php

There is some cases that this could be unset

Possible warning

---

widgets/so-contact-widget/styles/default.less

The submit button in contact widget has an incorrect LESS variable.

Fixed incorrect LESS variable.

---

base/inc.php
base/inc/fields/css/so-measurement-field.css
base/inc/fields/css/so-measurement-field.less
base/inc/fields/factory.class.php
base/inc/fields/measurement.class.php
base/inc/fields/media.class.php
base/siteorigin-widget.class.php
tests/base/inc/fields/test-base.class.php
tests/base/inc/fields/test-link.class.php
tests/base/inc/fields/test-media.class.php
tests/base/inc/fields/test-repeater.class.php
tests/bootstrap.php
widgets/so-features-widget/so-features-widget.php
widgets/so-features-widget/styles/features.less
widgets/so-headline-widget/so-headline-widget.php
widgets/so-headline-widget/styles/sow-headline.less

There are a couple of things which can be refactored. For example, the Google font import code is now duplicated in Features widget and Headline widget and perhaps how the measurement value is obtained when using the new measurement field.

Fb874 wb features text size

---

.editorconfig
build-config.js
widgets/contact/contact.php
widgets/contact/js/contact.js
widgets/contact/tpl/default.php

Resolves issues #34 and #35 as well as an issue I picked up with having multiple recaptchas on a page.

Contact form fixes

---

widgets/editor/editor.php

Fix of #47 - SO Editor seems to remove newlines in code formatting.

Fix of #47 - SO Editor seems to remove newlines in code formatting.

---

widgets/contact/contact.php

This resolves GH-68, GH-66 and GH-65.

Fix sanitization in the contact form

---

so-widgets-bundle.php

This resolves GH-82. Basically just moved the migration function into the get_active_widgets function and added some caching to ensure there isn't much of a performance hit.

Moved widget ID migration

---

widgets/price-table/styles/atom.less
widgets/price-table/tpl/atom.php

To resolve GH-72. Ensure feature icons always vertically centered, alongside feature text.

Fix Price Table feature icons alignment

---

widgets/hero/hero.php
widgets/hero/styles/default.less

To resolve GH-145. Pretty straightforward.

Color fields for setting heading and text colors in Hero widget.

---

widgets/features/features.php
widgets/features/tpl/base.php

Added a select field so users can choose from registered image sizes. 
To resolve GH-137, GH-138.

Allow user to select size for uploaded icon image.

---

widgets/icon/icon.php
widgets/icon/styles/sow-icon.less
widgets/icon/tpl/icon.php

Icon widget.

---

base/inc/fields/measurement.class.php
widgets/contact/contact.php
widgets/contact/styles/default.less

To resolve GH-69. Field for adding descriptions containing HTML below contact form fields.

Contact Form: field descriptions

---

base/inc/fields/measurement.class.php
widgets/button/button.php
widgets/button/styles/atom.less
widgets/button/styles/flat.less
widgets/button/styles/wire.less
widgets/button/tpl/base.php

To resolve GH-153. Can manually set width or leave width field blank to resize to content.

Button widget width

---

base/inc/fields/siteorigin-widget-field-class-loader.class.php
widgets/contact/contact.php
widgets/contact/fields/contactform-base.class.php
widgets/contact/fields/contactform-checkboxes.class.php
widgets/contact/fields/contactform-email.class.php
widgets/contact/fields/contactform-name.class.php
widgets/contact/fields/contactform-select.class.php
widgets/contact/fields/contactform-subject.class.php
widgets/contact/fields/contactform-text.class.php
widgets/contact/fields/contactform-textarea.class.php

Refactored contact form fields  to use autoloaded OO classes with render functions. Works with the same autoloader as used by admin form fields.

Contact Form field refactor

---

widgets/video/tpl/default.php
widgets/video/video.php

Update video widget to allow setting multiple sources to support various OSes / browsers etc.

Video player multiple sources

---

base/inc/fields/image-size.class.php
widgets/features/features.php
widgets/image-grid/image-grid.php
widgets/image/image.php

Image size field

---

widgets/contact/tpl/default.php

Vulnerable file **/so-widgets-bundle/widgets/contact/tpl/default.php** do not properly escape REQUEST_URI that makes possible **XSS** attack. Fix this filtering the final url via **esc_url()**

Fix XSS vulnerability

---

widgets/contact/styles/default.less

Resolves #199, it might be a better add sow-form-field to the recaptcha.

Add margin to recaptcha

---

widgets/features/tpl/default.php

Features: Use Measurement fields

---

base/siteorigin-widget.class.php

Add siteorigin_widgets_less_compiler filter to apply custom settings like include paths, compression etc.

New siteorigin_widgets_less_compiler filter

---

widgets/contact/contact.php

This PR changes all references of reCAPTCHA in the contact widget to the correct stylized version

Contact: Change references to reCAPTCHA to the correct stylization

---

base/siteorigin-widget.class.php

Throw less compiler errors in debug mode

---

widgets/social-media-buttons/tpl/default.php

trim network url and update spacing

---

widgets/cta/css/style.css
widgets/cta/css/style.less
widgets/cta/cta.php
widgets/cta/styles/default.less
widgets/cta/tpl/default.php

Resolves #254 
This PR will allow users to change the title and subtitle font. It doesn't have a default defined to allow the theme styling to be taken in. It also lays the groundwork for adding support for different header levels (if desired).

CTA: Add design setting to change title and subtitle colors

---

widgets/social-media-buttons/social-media-buttons.php
widgets/social-media-buttons/tpl/default.php

Resolves #262.
This adds a widget title field and adds title (the actual attribute) fields for the social buttons.

Social: Add title fields

---

widgets/features/features.php
widgets/features/tpl/default.php

Features: Add title text field for features

---

base/inc/widget-manager.class.php

Widget Manager: Apply realpath() to $path for get_class_from_path()

---

widgets/button/button.php
widgets/button/styles/atom.less
widgets/button/styles/flat.less
widgets/button/styles/wire.less

This PR will add the ability to allow users to set the font family of the button.

Button Widget: Add Font setting

---

widgets/google-map/google-map.php
widgets/google-map/tpl/static-map.php

This PR adds the ability to set a link for the static map. Includes option to open in new window.

Google Maps: Add ability to set link for Static Map

---

base/inc/post-selector.php

Seems odd to allow people to filter this on a global level.

Post Selector: Add filter for returned query

---

base/inc/fields/js/tinymce-field.js
base/js/admin.js
base/siteorigin-widget.class.php
compat/beaver-builder/beaver-builder.php
compat/builders.php
compat/compat.php
compat/elementor/elementor.php
compat/elementor/styles.less
so-widgets-bundle.php
widgets/video/video.php

Some changes to Beaver Builder compat too, so that the active builder's compat code is loaded as early as possible and then each can decide for itself which hooks to use for initialization etc.

Compatibility with Elementor

---

widgets/headline/headline.php
widgets/headline/styles/default.less
widgets/headline/tpl/default.php

This PR allows users to link the headline widget text to specific pages, without using HTML. It also allows them to adjust the hover color.

Headline: Add Ability to Link Headlines

---

widgets/taxonomy/taxonomy.php
widgets/taxonomy/tpl/default.php

This will allow users to set the taxonomy links to open in a new tab.

Taxonomy: New Window Setting

---

base/inc/widgets/base-slider.class.php

Resolves #108.
Setting it to 0 prevents the slider from working correctly.

Slider: Account for 0 speed

---

widgets/contact/contact.php
widgets/contact/styles/default.less

This PR adds the following field design settings.
- font 
- font size
- colors
- margin
- padding
- background
- Border
- Border width
- Border style
- Border Rounding
These design settigns are applied to input, textarea and datetime fields.

Contact: Add Field Design Settings

---

admin/tpl/admin.php
base/siteorigin-widget.class.php
widgets/google-map/google-map.php

Resolves #249. Finally. :sweat_smile:

Google Maps widget now has a global API key setting.

---

widgets/button/button.php
widgets/button/tpl/default.php

Resolves #227 
Also includes a small refactor to make more use of `get_template_variables` in the button widget.

Button: Added `rel` attribute

---

base/base.php
base/inc/shortcode.php

This is to support a new mode Page Builder has where it creates a special version of the content to store in post_content.

Add support for Page Builder database render

---

base/js/admin.js
widgets/contact/contact.php
widgets/contact/fields/name.class.php
widgets/contact/fields/subject.class.php
widgets/contact/fields/text.class.php
widgets/contact/fields/textarea.class.php
widgets/contact/styles/default.less

Resolves #169 
Option to display asterisks on required fields and displays legend above the form when it's enabled.
E.g.

Required field indicators

---

widgets/contact/styles/default.less

50% is way too high. 20% is also more in line with the border's lightening also.

Contact: Reduced lighten intensity of disabled button styling

---

widgets/google-map/google-map.php
widgets/google-map/js/js-map.js

Now you can define a custom icon per map marker.

Google Map Widget optimization - Custom Marker Icon for each marker

---

base/inc/fields/css/date-range-field.less
base/inc/fields/date-range.class.php
base/inc/fields/js/date-range-field.js
base/inc/fields/posts.class.php
base/inc/post-selector.php

To resolve #466. Allow selection of a date range relative to today.

Posts Selector Relative Dates

---

widgets/editor/editor.php

Fixes #454. Moved all text processing inside cache render conditional and correct order of processing calls.

Editor: prevent text processing for cache and post content rendering.

---

widgets/testimonial/testimonial.php

[Reported here](https://siteorigin.com/thread/sow-testimonials-incorrect-label-admin-interface/).

Testimonial: Corrected typo in description and corrected formatting

---

base/inc/widgets/base-slider.class.php

Resolves #359.
@gregpriday Would it be a good idea to check the video URL for the selected file type? It could be an in for adding third-party JavaScript.

Slider Background Video: Try embedding the video if oEmbed fails

---

admin/tpl/admin.php
base/inc/widget-manager.class.php
so-widgets-bundle.php

Fixes #510 
This allows the Global Widget Settings fields to work. It will also correct a lot of pathing comparison issues.

Widget Manager Path Comparison fix

---

widgets/features/styles/default.less

Features: Fixes margin causing extended page

---

widgets/hero/hero.php

This PR add a form field to select the format of image in the background of each frame.
It is backward compatible (default value is "Full").

add ability to select an image size on hero widget

---

admin/tpl/admin.php
base/inc/fields/builder.class.php
base/inc/fields/media.class.php
base/inc/fields/posts.class.php
base/siteorigin-widget.class.php
base/tpl/posts-selector/post.html
js/slider/jquery.slider.js
so-widgets-bundle.php
widgets/accordion/accordion.php
widgets/button/button.php
widgets/contact/contact.php
widgets/features/tpl/default.php
widgets/google-map/google-map.php
widgets/google-map/tpl/static-map.php
widgets/headline/tpl/default.php
widgets/icon/tpl/default.php
widgets/image-grid/image-grid.php
widgets/image/image.php
widgets/layout-slider/layout-slider.php
widgets/price-table/tpl/atom.php
widgets/simple-masonry/simple-masonry.php
widgets/slider/slider.php
widgets/social-media-buttons/tpl/default.php
widgets/taxonomy/tpl/default.php
widgets/testimonial/tpl/default.php

[Reported here](https://siteorigin.com/thread/widget-image-security-problem-no-relnoopener-tag/)
Reference: https://mathiasbynens.github.io/rel-noopener
[Slack Reference](https://siteorigin.slack.com/archives/C02SXRL8N/p1509362961000191)

Add noopener for all instances of _blank

---

js/slider/jquery.slider.js

Somehow the merge didn't go through correctly in #588. Sorry. :(

Corrected Slider JS error.

---

admin/tpl/admin.php

Fixes #598. Issue was caused by this commit https://github.com/siteorigin/so-widgets-bundle/commit/6791c0ea4de736d3ee59589b5008078a2d6941ab

Widgets Page: Fix missing icon issue on windows

---

widgets/accordion/styles/default.less

Added Overflow for Accordion to prevent Image Overlap

---

admin/tpl/admin.php
so-widgets-bundle.php

Global Settings: Add support for global settings added by themes

---

widgets/accordion/tpl/default.php

Accordion: Don't output widget title if not set

---

widgets/button/button.php
widgets/button/css/style.less
widgets/button/styles/atom.less
widgets/button/styles/flat.less
widgets/button/styles/wire.less

Button: Icon placement setting

---

widgets/hero/hero.php
widgets/hero/styles/default.less

Hero adjustments

---

widgets/contact/contact.php
widgets/contact/styles/default.less
widgets/contact/tpl/default.php

Resolves the following issues: #198, #629, #197 and #139

Contact adjustments

---

widgets/hero/hero.php
widgets/hero/styles/default.less

... that prevented users from removing the shadow altogether

Hero: Corrected paragraph shadow check

---

widgets/image/image.php
widgets/image/styles/default.less

This will allow users to adjust the alignemnt of the SiteOrigin Image Title alignment.

Image: Add title alignment setting

---

widgets/social-media-buttons/data/networks.php

This request adds the WhatsApp social icon and resolves #684

Adds WhatsApp Social Network

---

base/inc/fields/posts.class.php

Posts field - taxonomy description

---

compat/beaver-builder/styles.less

Beaver Builder: Force icon fonts

---

widgets/social-media-buttons/data/networks.php
widgets/social-media-buttons/social-media-buttons.php
widgets/social-media-buttons/tpl/default.php

This PR adds a new Phone button and resolves #725 while also accounting for the addition of the Phone "network".

Social Media Buttons: Add Phone and resolve #725

---

widgets/accordion/styles/default.less

This PR will automatically expand all Accordion items when the user prints the page.

Accordion: Expand items automatically when user is printing

---

js/sow.google-map.js

Related to #731. Don't consider merge until feedback from @vollyimnetz.

Google Maps - limit geocode rate limit attempts

---

widgets/tabs/js/tabs.js
widgets/tabs/tpl/default.php

This PR will allow the user to tab through the tabs. This PR is for accessibility reasons.

Tabs: Allow tabs to change tabs

---

base/inc/fields/builder.class.php

Fix fatal error with builder field for users using PHP < 5.4

---

base/base.php

This PR is a replacement of #765 without the additional changes.

Remove redundant TinyMCE Enqueue

---

js/slider/jquery.slider.js

Disable jQuery Cycle2 slider logging

---

base/siteorigin-widget.class.php

[Requested here](https://siteorigin.com/thread/widgets-actions-after-save-delete-style-files/)

Hooks for other plugins to monitor creation and deletion of stylesheets

---

widgets/social-media-buttons/data/networks.php

Add Bandcamp, Goodreads, Strava, and Telegram networks.
Resolve #689

Social Media Buttons - add Four networks

---

compat/beaver-builder/styles.less

Beaver Builder: Update Font Awesome CSS

---

widgets/post-carousel/tpl/base.php
widgets/post-carousel/tpl/carousel-post-loop.php

Resolves issues where accessibility tools will flag these as non-descriptive links.

Post Carousel: Label navigation and carousel items

---

widgets/tabs/styles/default.less

Tabs: Set default tab position to top

---

widgets/contact/tpl/default.php

Contact: Prevent double nonce

---

widgets/accordion/js/accordion.js
widgets/accordion/styles/default.less
widgets/accordion/tpl/default.php

This PR is a version of #750 for the Accordion widget. It's built with WAI-ARIA in mind. Please refer to [this section](https://www.w3.org/TR/wai-aria-practices/#accordion) for information on accordions.

Accordion: Keyboard navigation

---

widgets/testimonial/testimonial.php

Minor label adjustments as discussed in https://github.com/siteorigin/so-widgets-bundle/issues/677.

Minor label adjustments

---

widgets/accordion/js/accordion.js

Accordion: Check if if anchor is present in URL and scroll to Accordion item

---

widgets/social-media-buttons/data/networks.php

Colors based on [Brand Guidelines](https://www.skype.com/en/legal/brand-guidelines/).

Social Media Buttons: Add Skype network

---

widgets/contact/styles/default.less

Contact: Apply Field Label color to Radio and Checkboxes labels

---

base/inc/fields/css/measurement-field.less

Resolves https://github.com/siteorigin/so-widgets-bundle/issues/926.
@AlexGStapleton Can you see an issue with doing this?

Removed static height declaration

---

base/css/admin.less

Added right margin to color picker input

---

base/inc/fields/css/media-field.less

Resolves https://github.com/siteorigin/so-widgets-bundle/issues/944
@AlexGStapleton It isn't perfect for all resolutions but I think it's good enough.

Better render media search field for mobile

---

widgets/hero/styles/default.less

"Pre-fill" hero if height is set

---

widgets/features/features.php
widgets/features/styles/default.less
widgets/features/tpl/default.php

SiteOrigin Features: Allow Selection of Different Title Header Levels

---

widgets/layout-slider/styles/default.less

Version of #939 for the Layout Slider. Outside of the comment, no special changes were required to get the LESS working with the Layout Slider.

"Pre-fill" Layout Slider if height is set

---

widgets/features/features.php
widgets/features/tpl/default.php

This PR adds fallback support for the SiteOrigin Features Icon Image field.

Features: Add Fallback support for Icon Image

---

base/inc/fields/css/measurement-field.less

@AlexGStapleton Can you see any issue with this change?
Resolves https://github.com/siteorigin/so-widgets-bundle/issues/951.

Change measurement field to use only right margin

---

base/inc/routes/siteorigin-widgets-resource.class.php
base/siteorigin-widget.class.php

Account for false values when setting default values rather than just empty values

---

widgets/testimonial/testimonial.php
widgets/testimonial/tpl/default.php

Add Testimonial Fallback Image support

---

widgets/contact/contact.php

Resolves #958 . Checks that there are at least 3 digits in a phone number field.

Contact form: Add arbitrary validation for phone numbers.

---

base/inc/routes/siteorigin-widgets-resource.class.php
base/siteorigin-widget.class.php
widgets/editor/editor.php

Editor widget: Process more quicktag in block editor.

---

base/inc/routes/siteorigin-widgets-resource.class.php
base/inc/widget-manager.class.php
base/siteorigin-widget.class.php
compat/block-editor/widget-block.js
compat/block-editor/widget-block.php
widgets/contact/contact.php
widgets/editor/editor.php
widgets/post-carousel/post-carousel.php
widgets/price-table/price-table.php

Resolve #956 
Append third party widget author names to distinguish between SiteOrigin and third party widgets.

Widget block show author

---

base/inc/fields/css/media-field.less

Resolves https://github.com/siteorigin/so-widgets-bundle/issues/972

Updated media button right margin

---

widgets/accordion/styles/default.less
widgets/accordion/tpl/default.php

Requires: siteorigin/siteorigin-premium/pull/345

SO Premium Accordion: CSS for Custom icons

---

widgets/tabs/styles/default.less
widgets/tabs/tpl/default.php

Requires siteorigin/siteorigin-premium/pull/344

SO Premium Tabs: CSS for Custom icons

---

widgets/accordion/styles/default.less
widgets/tabs/styles/default.less

Tabs and Accordion: Add Icon Spacing

---

widgets/testimonial/styles/default.less
widgets/testimonial/tpl/default.php

Testimonial: Enforce Image Size for Square Container

---

widgets/hero/hero.php
widgets/hero/styles/default.less

Resolves https://github.com/siteorigin/so-widgets-bundle/issues/986
@Misplon You mentioned you wanted to see how it works before working on the description. How does the following (very rough suggestion) sound?
> Please note that Extra top padding may cause the slide contents to be slightly off-centered.

Hero: Add "Vertically align slide contents" setting

---

widgets/layout-slider/layout-slider.php

Resolve https://github.com/siteorigin/so-widgets-bundle/issues/1003

Layout Slider: Fetch Frame titles based on priority

---

base/js/admin.js

[Mentioned here](https://github.com/siteorigin/so-widgets-bundle/pull/1008#issuecomment-603068404).

Revert repeater label to the default if no item label found

---

widgets/slider/slider.php

Resolve https://github.com/siteorigin/so-widgets-bundle/issues/1002

Slider: Set frame titles based on priority list

---

icons/fontawesome/filter.php

Font Awesome: Re-order style ordering

---

widgets/contact/contact.php
widgets/contact/fields/select.class.php

This PR will move the field label inside of the select if the `Label Position` is set to `Placeholder`.

Contact: Add placeholder support to dropdown select field

---

widgets/hero/hero.php

https://github.com/siteorigin/so-widgets-bundle/pull/1015#discussion_r404379900

Hero: Rename vertical align setting to make more sense

---

widgets/hero/hero.php
widgets/layout-slider/layout-slider.php
widgets/layout-slider/styles/default.less

Resolve https://github.com/siteorigin/so-widgets-bundle/issues/1014

Layout Slider: Add Setting that Allows Vertical Alignment

---

base/inc/attachments.php

[Reported here](https://github.com/siteorigin/so-widgets-bundle/pull/1018#pullrequestreview-392855243)

Remove redundent code

---

base/base.php
widgets/icon/icon.php
widgets/icon/tpl/default.php

This PR adds a title field to the Icon widget which uses the title attribute to output the title.
Related https://github.com/siteorigin/siteorigin-premium/issues/359

Icon Widget: Add Title Field

---

widgets/price-table/tpl/atom.php

Related: https://github.com/siteorigin/siteorigin-premium/pull/385

Price Table: Add Hover Text using Title Attribute

---

widgets/post-carousel/css/style.less

Resolve https://github.com/siteorigin/so-widgets-bundle/issues/1038

Post Carousel: If a title is set, inline the navigation

---

build-config.js

Required for https://github.com/siteorigin/plugin-build/pull/13

Add googleFonts build config

---

base/inc/fonts.php

Resolves #1043
Related https://github.com/siteorigin/plugin-build/pull/13

Update Google Fonts

---

widgets/testimonial/css/style.less

Resolve https://github.com/siteorigin/so-widgets-bundle/issues/1053
I tried each of the Testimonial Layout and User Potion and didn't notice any issues as a result of this change.

Testimonials: Set testimonial text width

---

build-config.js

This PR is required for [the updateFontAwesome build task](https://github.com/siteorigin/plugin-build/pull/14) to work.

editor-config: Add fontAwesome config

---

css/slider/slider.less
icons/elegantline/style.css
icons/fontawesome/style.css
icons/genericons/style.css
icons/icomoon/style.css
icons/ionicons/style.css
icons/typicons/style.css

here the font-display block stylings

added Font display: block

---

widgets/features/css/style.less
widgets/post-carousel/css/style.less

[Related note](https://github.com/siteorigin/so-widgets-bundle/pull/1067#issuecomment-642168910)

Set font-display on remaining @font-face

---

widgets/button/button.php
widgets/button/styles/atom.less
widgets/button/styles/flat.less
widgets/button/styles/wire.less

I've added hover button stylings because sometimes you want to have another hover effect.
For example if i've an wire button with white text white background - the hover would be white on white.
Now you can adjust the button hover colors.

Added hover button stylings

---

compat/block-editor/widget-block.php

Resolve https://github.com/siteorigin/so-widgets-bundle/issues/1068

SiteOrigin Widgets Block: Add Block CSS Classes

---

widgets/simple-masonry/js/simple-masonry.js
widgets/simple-masonry/simple-masonry.php
widgets/simple-masonry/tpl/default.php

Resolve https://github.com/siteorigin/so-widgets-bundle/issues/1052

Simple Masonry: External Image Support

---

widgets/post-carousel/post-carousel.php
widgets/post-carousel/tpl/carousel-post-loop.php

Resolve https://github.com/siteorigin/so-widgets-bundle/issues/1082

Post Carolusel: Add Link Target

---

base/css/admin.less
base/inc/fields/css/date-range-field.less
base/inc/fields/css/measurement-field.less
base/inc/fields/css/media-field.less
base/inc/fields/css/radio.less

Resolve https://github.com/siteorigin/so-widgets-bundle/issues/1087

WB Form Field Mobile Adjustments

---

widgets/button/button.php

Resolve https://github.com/siteorigin/so-widgets-bundle/issues/1095

Button LESS Fix

---

widgets/social-media-buttons/data/networks.php

Require https://github.com/siteorigin/so-widgets-bundle/pull/1093

Social Media Buttons: Add Tiktok

---

widgets/features/styles/default.less

Reverts siteorigin/so-widgets-bundle#1075

Revert "Features: Prevent Text Overlapping Icon"

---

widgets/button/styles/atom.less
widgets/button/styles/flat.less
widgets/button/styles/wire.less

Resolve https://github.com/siteorigin/so-widgets-bundle/issues/1103

Button: Set Hover Background Color Defaults

---

widgets/post-carousel/js/carousel.js

This PR improves support for multiple post carousels on the same page but setting variables as needed. This ensures they're correct and relevant when used.

Post Carousel: Improve Multiple Carousel and Mobile Support

---

widgets/post-carousel/js/carousel.js
widgets/post-carousel/tpl/base.php

Resolve https://github.com/siteorigin/so-widgets-bundle/pull/1100#issuecomment-662064082 https://github.com/siteorigin/so-widgets-bundle/pull/1100#discussion_r459005793
This PR also finds the ItemWidth as needed rather than pre-defining it.

Post carousel: Contextualize variables as needed

---

widgets/contact/contact.php

Resolve https://github.com/siteorigin/so-widgets-bundle/issues/1112
I ran a few tests and didn't come across any issues by making this change.

Contact: Pass correct fields to Akismet

---

base/inc/widgets/base-slider.class.php
js/slider/jquery.slider.js

This PR resolves https://github.com/siteorigin/so-widgets-bundle/issues/1101 https://github.com/siteorigin/so-widgets-bundle/issues/982 https://github.com/siteorigin/so-widgets-bundle/issues/920

Sliders: Add Autoplay and Autoplay Pause on Hover settings

---

widgets/features/tpl/default.php

This PR allows shortcodes to be added to the Feature text field.

Features: Allow shortcodes to be used in the text field

---

widgets/accordion/accordion.php

Resolve https://github.com/siteorigin/so-widgets-bundle/issues/1021

Accordion allow line breaks dont double escape

---

base/inc/post-selector.php

Resolve https://github.com/siteorigin/so-widgets-bundle/issues/1089

Post Selector: Add optional parameter to exclude current post

---

widgets/post-carousel/js/carousel.js

Resolve https://github.com/siteorigin/so-widgets-bundle/pull/1116#issuecomment-669134860

Post Carousel: Use totalposts for navigation visibility conditional

---

base/js/admin.js

Resolve https://github.com/siteorigin/so-widgets-bundle/issues/1114

State Emitter: show/hide animation

---

widgets/contact/contact.php
widgets/contact/styles/default.less

Resolve https://github.com/siteorigin/so-widgets-bundle/issues/988

Contact: Add Field max width setting

---

widgets/post-carousel/css/style.less
widgets/post-carousel/post-carousel.php
widgets/post-carousel/styles/default.less

Resolve https://github.com/siteorigin/so-widgets-bundle/issues/1126

Post Carousel: Add Design Settings

---

widgets/post-carousel/js/carousel.js

Resolve https://github.com/siteorigin/so-widgets-bundle/issues/1133

Post Carousel: Ensure correct navigation is hidden

---

widgets/post-carousel/tpl/carousel-post-loop.php

Resolve https://github.com/siteorigin/so-widgets-bundle/issues/1154
The second commit is more about tidying up as things aren't very readable without it.

Post Carousel: Add link target to items with thumbnail

---

base/js/admin.js

Resolve https://github.com/siteorigin/so-widgets-bundle/issues/1167

State Emitter: Don't rely on ToggleFade.

---

widgets/button/button.php

Resolve https://github.com/siteorigin/so-widgets-bundle/issues/1156

Button: Add Download Setting

---

widgets/accordion/accordion.php
widgets/accordion/js/accordion.js
widgets/tabs/js/tabs.js
widgets/tabs/tabs.php

Resolve https://github.com/siteorigin/so-widgets-bundle/issues/1163

Tab & Accordion: Add setting to disable scroll

---

widgets/contact/contact.php

Resolve https://github.com/siteorigin/so-widgets-bundle/issues/1145
I checked all labels and none of them had non-standard sentence cases.

Contact: Resolve Setting Cases

---

widgets/post-carousel/css/style.less
widgets/post-carousel/js/carousel.js
widgets/post-carousel/post-carousel.php
widgets/post-carousel/tpl/base.php

Resolve https://github.com/siteorigin/so-widgets-bundle/issues/1172

Post Carousel: Center Items setting

---

widgets/post-carousel/post-carousel.php

This PR uses https://github.com/siteorigin/so-widgets-bundle/pull/1176 to implement the label suggested [here](https://github.com/siteorigin/so-widgets-bundle/pull/1177#issuecomment-712853857).

Post Carousel: Change Posts Per Page Label

---

base/inc/fields/js/tinymce-field.js

This PR resolves an issue that can result in the Add Media Buttons sometimes not working.

TinyMCE: Update Add Media Button for ID

---

js/sow.google-map.js

This PR adds an event that triggers after all of the Google Maps have finished being set up.

Map: Add maps_loaded event

---

widgets/post-carousel/post-carousel.php

Resolve https://github.com/siteorigin/so-widgets-bundle/issues/1211

Post Carousel: Give Posts Per Load Setting a Description

---

widgets/google-map/google-map.php

Maps: Global Settings Prompt

---

widgets/image-grid/image-grid.php

Requires https://github.com/siteorigin/so-widgets-bundle/pull/1198

Image Grid: Use Image Title if set

---

widgets/social-media-buttons/data/networks.php

Resolve https://github.com/siteorigin/so-widgets-bundle/issues/1216

Social Media Buttons: Add Discord

---

base/inc/fonts.php

(this was done using the build task)

 Update Google Fonts

---

base/base.php
base/inc/actions.php
base/inc/attachments.php
base/inc/fields/code.class.php
base/inc/fields/date-range.class.php
base/inc/fields/media.class.php
base/inc/fields/slider.class.php
base/inc/fields/textarea.class.php
base/inc/fields/tinymce.class.php
base/inc/widgets/base-slider.class.php
widgets/features/tpl/default.php
widgets/headline/headline.php
widgets/hero/hero.php
widgets/image-grid/image-grid.php
widgets/image-grid/tpl/default.php
widgets/layout-slider/layout-slider.php
widgets/simple-masonry/simple-masonry.php
widgets/slider/slider.php
widgets/testimonial/testimonial.php

WB version of https://github.com/siteorigin/siteorigin-panels/pull/835

Replace older-style PHP type conversion functions with type casts.

---

base/js/admin.js

This PR improves support for the external media field. It ensures that the fallback will be checked correctly. It also prevents a situation where the value will be set to `0`.
Please test using https://github.com/siteorigin/so-widgets-bundle/pull/1224.

State Emitter: Improve Media Field External Suport

---

compat/block-editor/widget-block.js
compat/block-editor/widget-block.php

Resolve https://github.com/siteorigin/so-widgets-bundle/issues/836

Widget Block: Store and serve rendered widget

---

widgets/post-carousel/css/style.less
widgets/post-carousel/post-carousel.php
widgets/post-carousel/styles/default.less

Resolve https://github.com/siteorigin/so-widgets-bundle/issues/908

Post Carousel: Add Overlay Hover Opacity Setting

---

widgets/contact/contact.php

[Suggested here](https://github.com/siteorigin/so-widgets-bundle/issues/894#issuecomment-755287683)
I went with `Required field` for consistency.

Contact: Set Missing message default value

---

widgets/google-map/google-map.php

- button text color
- button text hover color
- button background color
- button background hover color
Requires: https://github.com/siteorigin/so-widgets-bundle/pull/1205

Map Content: Add Button Styles Settings

---

base/js/admin.js

Resolve https://github.com/siteorigin/so-widgets-bundle/issues/1196

Repeater TinyMCE: Copy the contents of the text field

---

widgets/contact/contact.php

Resolve https://github.com/siteorigin/so-widgets-bundle/issues/893

Contact: Nest Required Indicater

---

base/js/admin.js
widgets/slider/slider.php
widgets/slider/styles/default.less

Resolve https://github.com/siteorigin/so-widgets-bundle/issues/1189
Requires https://github.com/siteorigin/so-widgets-bundle/pull/1224

Slider: Add Height Setting if Foreground Image is set

---

base/inc/fields/css/image-size-field.less
base/inc/fields/image-size.class.php
base/inc/fields/js/image-size-field.js

Resolves #1241
Related links:
[Demo PR](https://github.com/siteorigin/so-widgets-bundle/pull/1244) (requires this PR also - use this for testing)
[Docs](https://github.com/siteorigin/docs/pull/92)

Image: Add Support for Custom Image Size

---

base/inc/fields/link.class.php
widgets/button/button.php
widgets/button/tpl/default.php

Resolve https://github.com/siteorigin/so-widgets-bundle/issues/500
Admittedly, only shortcodes that return a URL will work as expected.

Button: Allow shortcodes in Destination URL field

---

readme.txt

New screenshots are on my to-do list but it's worthwhile pushing this change. I won't push a release, just an update to the readme file in the trunk and tags folder. Let me know if you want any changes.

Readme improvements

---

base/inc/fields/js/tinymce-field.js
base/inc/fields/tinymce.class.php

Resolve https://github.com/siteorigin/so-widgets-bundle/issues/903

TinyMCE: Add media_buttons parameter

---

widgets/contact/contact.php
widgets/contact/fields/number.class.php

This PR adds a number field as a Contact Form Field Type.

Contact: Add Number Field

---

compat/block-editor/widget-block.js
compat/block-editor/widget-block.less
compat/block-editor/widget-block.php

Resolve: https://github.com/siteorigin/so-widgets-bundle/issues/968
(please excuse mouse cursor placement due to a recording issue)

SO Widget Block: Switch from Select to ComboboxControl

---

widgets/slider/slider.php

[Reported here](https://siteorigin.com/thread/siteorigin-widgets-bundle-1-18-1/). Will submit for review once user replies.

Slider: Only apply foreground height if background_image is set

---

widgets/video/js/so-video-widget.js

FitVids doesn't need a visible video to work as expected.

Video: Setup FitVids even if video isn't visible

---

base/inc/video.php

YouTube requires the video to be in a playlist for it to loop so this PR adds the current video to a playlist containing itself. There may be a brief period where you'll see a flash of a buffering icon, that's unavoidable.
Test using https://github.com/siteorigin/so-widgets-bundle/pull/1271

Video Embed: Add YouTube Loop Support

---

base/inc/widgets/base-slider.class.php

Resolves: https://github.com/siteorigin/so-widgets-bundle/issues/1299

Update slider background video autoplay setting description

---

widgets/video/tpl/default.php
widgets/video/video.php

Requires https://github.com/siteorigin/so-widgets-bundle/pull/1298
Prior to this PR, the Loop setting would disappear if an External Video was selected.

Video Player: Allow External Videos to Loop

---

widgets/image-grid/image-grid.php

Resolve an invalid loading attribute when a local image is used.

Image Grid: Avoid Loading Attr Issue When Using Local Image

---

widgets/image/image.php

Hey that should be $instance['size_height'] right?
If not, deleted my request.

Update Instance size to height

---

admin/admin.js

This PR will ensure more consistent box-sizing. Please refer to the individual commits for more information.

Further widgets page sizing adjustments

---

widgets/image-grid/image-grid.php
widgets/image-grid/styles/default.less

Resolve https://github.com/siteorigin/so-widgets-bundle/issues/1324

Image Grid Alignment Settings

---

widgets/hero/hero.php

The alignment is handled via the Hero frame directly.

Hero: Remove Button Align Setting

---

widgets/image/image.php
widgets/image/tpl/default.php

This PR adds a setting to the Image widget called "Add link title to URL". This will allow the user to link the image title to the images URL.

Image: Add Link Title to URL Setting

---

base/css/admin.less

[Reported here](https://github.com/siteorigin/siteorigin-panels/pull/889#issuecomment-862360696).
Before:
After:

Vertically Center Posts Selector

---

widgets/headline/headline.php

Resolve https://github.com/siteorigin/so-widgets-bundle/issues/1346

Headline: Change the default headline to h2

---

widgets/image-grid/image-grid.php

Image Grid: Add "Image vertical alignment" description

---

widgets/features/features.php

Resolve https://github.com/siteorigin/so-widgets-bundle/issues/1348 as per our chat over Slack.

Features: Prevent Auto Page Builder Description

---

widgets/video/tpl/default.php
widgets/video/video.php

This setting will allow you to enable/disable video player controls.

Video Player: Add Video Controls Setting

---

base/css/admin.less
base/inc/fields/css/date-range-field.less
base/inc/fields/css/icon-field.less
base/inc/fields/css/image-radio-field.less
base/inc/fields/css/image-size-field.less
base/inc/fields/css/measurement-field.less
base/inc/fields/css/media-field.less
base/inc/fields/css/multi-measurement-field.less
base/inc/fields/css/multiple-media-field.less
base/js/admin.js
compat/block-editor/widget-block.php

This PR contains changes required for WB to be compatible with the new widgets interface.

5.8 Widgets Changes

---

widgets/testimonial/styles/default.less

Resolve https://github.com/siteorigin/so-widgets-bundle/issues/1365

Testimonials: Collapse to Column On Mobile

---

js/sow.google-map.js
widgets/google-map/fields/js/location-field.js

This PR resolves an issue where the location field won't work correctly on a new Block Editor powered page. To test it, create a new page, add a SiteOrign Widgets Block, select Google Maps and then try and type a location.

Block editor preview google maps fixes

---

base/inc/actions.php
base/inc/fields/js/autocomplete-field.js
base/js/admin.js

Resolve https://github.com/siteorigin/so-widgets-bundle/issues/1423
This PR will filter the posts listed in the Autocomplete field to only the current page WPML language.

WPML: Filter Autocompelete WPML Results Based on Page Language

---

widgets/price-table/price-table.php
widgets/price-table/styles/atom.less

This PR renames the `Header color` and `Featured header color` settings.
This PR also introduces three new text color settings:
- Header text color
- Featured header text color
- Feature text color

Price Table: Setting Rename and New Text Color Settings

---

base/inc/widgets/base-slider.class.php

Used by Layout Slider Anchor Tags. This PR is not able to be tested by itself as it's dependent on another PR.

Slider: If `anchor` is set, include in slider controls

---

base/inc/widgets/tpl/carousel.php
js/carousel.js
widgets/post-carousel/post-carousel.php
widgets/post-carousel/tpl/item.php

Resolve https://github.com/siteorigin/so-widgets-bundle/issues/1452
Please test that post featured images, external images, and the external URL work as expected. The external URL field will only be used if the external image isn't set.
This PR also ensures that the assigned image size is used for the fallback image.

Post Carousel: Add Support for Fallback External URL

---

widgets/anything-carousel/anything-carousel.php

We're adding the period separately.

Removed extra period

---

base/inc/widgets/base-carousel.class.php
base/inc/widgets/tpl/carousel.php
widgets/anything-carousel/styles/base.less
widgets/post-carousel/styles/base.less

Resolve https://github.com/siteorigin/so-widgets-bundle/issues/1466
Resolve https://github.com/siteorigin/so-widgets-bundle/issues/1467
To test this PR enable autoplay and disable the Navigation Arrows on mobile. Prior to this PR the autoplay wouldn't occur, after it will.

Post Carousel: Allow for Autoplay when nav arrows are hidden

---

base/inc/widgets/tpl/carousel.php
widgets/anything-carousel/styles/base.less

Resolve https://github.com/siteorigin/so-widgets-bundle/issues/1473
[Test Layout](https://drive.google.com/uc?id=1ySmPeoFxGinZVWEtKNbZN30oRXKe2Tkq)

Anything Carousel: Restore Autoplay If Nav Arrows Disabled

---

widgets/features/features.php
widgets/features/styles/default.less
widgets/features/tpl/default.php

This will inline column alignment to allow for columns to be sized correctly prior to CSS loading.
[Test Layout](https://drive.google.com/uc?id=1jrnoxZnIQsTcC1vo7XQp4XB68eMxtkWH)

Features: Inline Column Alignment

---

widgets/features/styles/default.less

This PR will center the feature icon on mobile when the container position is set to right or left. This will result in the same alignment as the top/bottom alignments.

Features: Center Align Left/Right Icon On Mobile

---

widgets/tabs/js/tabs.js
widgets/tabs/tabs.php

Tabs widget version of https://github.com/siteorigin/so-widgets-bundle/pull/1451.
Test snippet:
```
add_filter( 'siteorigin_widgets_tabs_scrollto_offset', function( $offset ) {
return 150;
} );
```

Add `siteorigin_widgets_tabs_scrollto_offset`

---

widgets/lottie-player/tpl/default.php

Resolve https://github.com/siteorigin/so-widgets-bundle/issues/1494

Lottie Player: Prevent Link From Covering Controls

---

widgets/social-media-buttons/styles/atom.less
widgets/social-media-buttons/styles/flat.less
widgets/social-media-buttons/styles/wire.less

[Reported here](https://github.com/siteorigin/so-widgets-bundle/pull/1491#issuecomment-1100895003)

Social Media BTN: Account for Twenty Fifteen Link `border-bottom` Override

---

widgets/accordion/js/accordion.js
widgets/tabs/js/tabs.js

This PR improves backwards compatibility for those not using the Anchor IDs addon. Test against https://github.com/siteorigin/so-widgets-bundle/pull/1488

Accordion & Tab: Improved Anchor ID Backwards Compat

---

base/base.php

This PR will hide icons from screen readers ([info](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-hidden)).

Icons: Hide From Screen Readers

---

base/inc/video.php
base/inc/widgets/base-slider.class.php
js/slider/jquery.slider.js

Resolve https://github.com/siteorigin/so-widgets-bundle/issues/1511
This PR adds automatic playing/pausing of YouTube and Vimeo background videos.

Slider: oEmbed YT/Vimeo Automatic Playing and Pausing

---

widgets/features/features.php
widgets/features/tpl/default.php

Resolve https://github.com/siteorigin/so-widgets-bundle/issues/1524

Features: Move Tag Setting to `Font Design > Title` Section

---

base/base.php

Don't display empty inline style tags.
When displaying inline style tags, check if the theme supports html5.

HTML Validation Improvements

---

widgets/blog/blog.php

Added a pagination-based setting class to `sow-nav-links`.

Added a pagination class to `sow-nav-links`

---

widgets/features/features.php
widgets/features/styles/default.less
widgets/features/tpl/default.php

Resolve https://github.com/siteorigin/so-widgets-bundle/issues/1535
Please test using all icon container positions.

Features: Add `Bottom align the More link text` setting

---

widgets/blog/styles/alternate.less

Resolve https://github.com/siteorigin/so-widgets-bundle/issues/1602
This PR will set the Featured Image to Full width on mobile.

Blog Alternate Full Width Featured Image on Mobile

---

widgets/post-carousel/post-carousel.php

This PR adds Widget Preview support for the Post Carousel widget.

Post Carousel: Add Widget Preview Support

---

widgets/google-map/styles/default.less

Resolve https://github.com/siteorigin/so-widgets-bundle/issues/1613

Google Maps: Prevent Maps Logo From Being Potentially Hidden

---

widgets/blog/styles/grid.less

Resolve https://github.com/siteorigin/so-widgets-bundle/issues/1625

Blog Grid: Resolve Responsive Collapse Issue

---

widgets/blog/blog.php
widgets/blog/data/templates.json
widgets/blog/tpl/offset.php

Resolve https://github.com/siteorigin/so-widgets-bundle/issues/1616. Supports all templates except for Portfolio - which can be done, it's just not clear how that would look.

Blog: Add `Post Tags` Setting

---

widgets/google-map/styles/default.less

Google Maps: Prevent Position Reset From Affecting Info Window

---

widgets/hero/styles/default.less

Related https://github.com/siteorigin/so-widgets-bundle/pull/1479

Hero: Only Override `max-height` Prefill on Mobile

---

icons/fontawesome/filter.php

This PR resolves the Gear icon and allows for it to be displayed on the frontend.

Font Awesome: Don't Migrate Gear(s) Icons
