siteorigin/so-widgets-bundle

so-widgets-bundle.php
I want to filter the capability of the admin page. At the moment it is not possible to access the page if DISALLOW_FILE_MODS is set to true. Would be nice to see it in the next release.
=> apply filter to capability of admin page

base/siteorigin-widget.class.php
Fixes #14 
I've wrapped the enqueued widget css url in set_url_scheme() as it will check if SSL is being used and correct the url to https if it is.
=> Use set_url_scheme() when enqueueing css

widgets/so-image-grid-widget/so-image-grid-widget.php, widgets/so-image-grid-widget/tpl/default.php
Changed the url input field type to 'link' to and added missing `<a>` tag to template.
=> FB 873: Image Grid widget URL field not working

widgets/so-google-map-widget/js/js-map.js
Hello.
We ran into an issue where the Google Map widget sometimes wouldn't appear. This turned out to be loadApi() which loads the required script and gives it the callback initialize() function. What would happen is that, depending on execution order, the initialize() function could be overwritten before the script the google script finished running and then the wrong function would be called.
The conflicting function with the same name initialize() was in the "UDG Tagging & Testing Extension" plugin, and this would get called instead of the intended one here. Therefore the map widgets would never appear.
My suggestion is to just rename the function to something more obscure and less likely to conflict. It's less of an issue with other function names as JavaScript scoping rules normally …
=> Prefix function name in Google Map widget

widgets/image/tpl/base.php
Wordpress 4.4 adds support for responsive images via srcset to images added through the visual editor. However, these changes don't get applied to the Site Origin Image Widget. This change uses the new Wordpress wp_get_attachment_image_srcset function to add the required attributes to the widget.
=> Add support for srcset to Image widget

widgets/editor/editor.php
Related to #43, I realized images from the editor widget weren't getting srcset attributes either. This PR fixes that for WP 4.4 while being backward compatible.
=> Updating wysiwyg editor images to be responsive

base/inc/fields/tinymce.class.php, widgets/google-map/google-map.php, widgets/google-map/js/js-map.js, widgets/google-map/tpl/js-map.php
To resolve issue #44 
Some refactoring to send map configuration options as single data attribute and separate markers and directions functions.
Fix for bug when using TinyMCE field in directions waypoints.
=> Allow LatLong input for Google Maps widget center and markers.

so-widgets-bundle.php
Hey folks!
Firstly, thanks for your great plugin!
I was creating a new widget this afternoon on a site and I hit a bug where activating a widget wouldn't actually save the activation. I noticed in the console that I was getting anything returned when I clicked activate so I started hunting down the issue and it turned out to be the default caps.
For our sites we have `define( 'DISALLOW_FILE_MODS', true );` set in `wp-config.php` so that clients can't update plugins however they can still alter settings. In that scenario they can get to the Plugins->SiteOrigin Widgets can they can click Activate and the plugin looks like it activated but when you hit refresh it's not.
To get around this `manage_options` is a more sensible capability to check for. It's an edge case but I think it's worth …
=> Alter the default caps

base/inc/post-selector.php
When multiple taxonomy terms are specified for a query, wordpress defaults to relation AND but my experience says the users mostly mean OR when they include multiple taxonomy terms. The use case of someone wanting to see all posts belonging to either category/term X or Y is much more common than someone wanting to create a query for a post which belongs to both category/terms X and Y, IMO. Pls review and merge if this seems right.
=> OR relation for multiple taxonomy terms

widgets/slider/slider.php
I was trying to use PNGs with transparent rounded corners and kept seeing a gray color behind them...this removes that color as default and instead doesn't pass a `background-color` attr to the frame element.
=> Default to no background color for slider frame instead of arbitrary gray

widgets/headline/headline.php
Adding the margin unit here causes the units to double up and thereby
breaking the CSS rule for the margin around the divider for the Headline
widget.
=> Fix issue where margin units were doubling causing broken margin rule in Headline Widget.

base/inc/post-selector.php, base/js/posts-selector.js
Use commas instead of ampersands as interim delimiter for additional query params. To resolve GH-124.
=> Fix post selector additional params field.

base/siteorigin-widget.class.php
Fall back to using `wp_cache` functions when `WP_Filesystem` not available.
To resolve GH-62.
=> WP_Filesystem fallback.

base/js/admin.js
To resolve GH-162.
It was simulating a click on the selected icon when choosing the icon family from the dropdown, which caused the icon grid to close. As far as I could see, the only purpose of this was to set the selected icon on the icon selector button.
=> Fix icon selector closing unexpectedly

widgets/contact/contact.php
To resolve GH-129. Use generic default when no subject input and no default subject.
Ensure the default subject is always used if available and subject not set.
=> Fix contact form failing when no subject input and no default subject.

base/css/admin.less, widgets/headline/headline.php
Everywhere the action order is: "Edit, Copy, Delete" except here.
Here is "Delete, Copy, Edit".
Don't know if this has a special reason and I'm the only one who always clicks on the wrong button but I think this should be the same everywhere.
Fixed that.
=> Update action order of widget field buttons

so-widgets-bundle.php, widgets/post-carousel/js/carousel.js
JS throws a `Uncaught TypeError: $$.swipe is not a function` error in some cases.
Wrapping method into a `typeof` check to avoid issues.
=> Adding fault tolerance to swipe method invocation

widgets/google-map/js/js-map.js
With this changeset any future uses of the Google Maps API should use the `js-map.js` script. If the required feature isn't available in `js-map.js`, it should be modified to include the required feature.
=> Consolidate Google Maps JS

base/siteorigin-widget.class.php
Actually use `$control_options` instead of `$widget_options`
for passing control options to parent constructor.
Original code has been in place since Nov 2014, so this fix could possibly break workarounds in other places. A compatibility fix is possible if deemed necessary.
=> SiteOrigin_Widget: Fix use of wrong variable

base/inc/fields/css/icon-field.less
Resolves #322.
CSS was written for a form field labeled icon and didn't allow different labels as a result.
=> Allow icon form field to use different labels

base/inc/fields/code.class.php, base/inc/fields/media.class.php
Google AppEngine does not auto-correct double slashes in a URL, the following one result in a 404 error:
`so-widgets-bundle/base/inc/fields//js/media-field.min.js?ver=1.6.5`
plugin_dir_url() already outputs the trailing slash so it's not needed in the string path.
=> Removed leading slash in paths after plugin_dir_url()

base/inc/post-selector.php
The sticky posts dropdown include sticky option is mislabeled. It should be labeled as only sticky as that's what it actually does. In other words, when the sticky posts option is set to include sticky it will only return sticky posts.
=> Change post selector sticky include to only

base/inc/fields/icon.class.php
Same issue as #325
"Google AppEngine does not auto-correct double slashes in a URL, [...] result[ing] in a 404 error"
=> Removed double slash from icon form field

base/inc/post-selector.php
Exactly the same issue as in siteorigin/siteorigin-panels#304
If a user adds post__not_in to the additional field it'll cause a fatal error as this line doesn't account for strings.
How to replicate this issue:
- Add the following into the additional field: post__not_in=372
That's it. This will cause this:
=> Corrected post__not_in issue for additional field

widgets/simple-masonry/js/simple-masonry.js
Resolve #281 
There's a chance the simple masonry won't resize on load. This PR ensures this isn't the case.
=> Simple Masonry: ensure masonry resize on load

base/siteorigin-widget.class.php
Widget less styles are filtered:
```
$less = apply_filters( 'siteorigin_widgets_styles', $less, $this->widget_class, $instance );
$less = apply_filters( 'siteorigin_widgets_less_' . $this->id_base, $less, $instance, $this );
```
If some filter returns empty string there is no reason to start compiler.
=> Do not compile empty less stylesheet

base/inc/post-selector.php
array_map is run but the results aren't stored in $query['post__in'].
=> Corrected array_map instance not updating variable

widgets/image/tpl/default.php
In a [recent commit](https://github.com/siteorigin/so-widgets-bundle/commit/a637b000e6090c956e983ead7a4c583c719cac30#diff-2c014a234ca0e640366c9f32dd8d18c3), the image title wasn't allowed to use HTML. This makes sense for the image title but it doesn't really make sense for the widget title (that's displayed) as it was previously allowed.
=> Image Widget: Allow title to contain HTML

widgets/contact/contact.php
sorry, I messed up with branches in my local repo, so I had to send this PR again.
it is the same as pull #280 which I messed up due to more commits and so I will close them.
again the info:
if you have multiple contact forms and want to have a fixed subject on each form, this case has not been catched in the code:
- do not define a subject field
- set a default subject field
if subject is not definad and default subject is defined that default subject will be used for the email.
this should basically fix #248
=> contact widget: add email default email subject if no subject defined in form

widgets/image/image.php, widgets/image/tpl/default.php
Resolves #210
This PR will allow for the image widget image to use the title / alt set in WordPress if the widget values aren't set.
=> Image Widget: use alt / title set via WP if not set

base/base.php
Resolves #277
Using is_ssl() is fine for most occurrences but when the website allows both http and https it falls flat if the version stored in the cache wasn't secure at the time of generation.
=> Google Font import: Replace is_ssl() with a HTTPS check of site_url()

widgets/image/image.php
#328 is a good idea, however it can produce some very unfriendly results like this: 
As such, this PR aims to only use the image title _if_ it's been changed. This solution falls over when the image is a cropped version of another image (as that's the full image name, with and without the extension removed) but I doubt that'll come up very often.
=> Image Widget: Prevent the default image title from being displayed

base/inc/actions.php
As odd as it may sound, checking purely for public to know if the post type is actually queryable or not is not very reliable.
For example, Meta Slider sliders are set to public but it's effectively private as publicly_queryable is set to false and exclude_from_search is set to true. In other words, this results in a 404 if the user links the link on the frontend.
=> Change links form field to only allow queryable posts

base/inc/post-selector.php
Exclude the current post (if applicable) to avoid any issues associated with showing the same post again.
Use case: A third party plugin doesn't handle things correctly and lets SiteOrigin Page Builder handle the post. This, in turn, will leed to an infinite loop.
I can't think of a valid reason as to why you would want the current post to appear so I feel it's safe to disregard it completely.
=> Post Selector: Exclude current post id

base/inc/fields/media.class.php
If library is set to all, convert it to a wildcard as all isn't valid
=> Media field: Convert all to *

base/siteorigin-widget.class.php
One of the only important functions on the SiteOrigin_Widget that does not have a filter to override it’s value is the “get_less_variables()” function. Normally this wouldn’t be such a big deal, but it’s very important that we be able to override this with a filter because it’s used by the “get_style_hash()” function which uniquely identifies the instance. This means that with the way it currently works, it’s impossible to add new editor fields to a widget via the “siteorigin_widgets_form_options” filter and have it work properly, because the new field values will not be properly factored into the widget’s style hash and it will be grouped with other widgets that have different values of the new field. I could add this new field by subclassing the widget class and overriding the …
=> Add new filters on get_less_variables and get_style_hash_variables

compat/beaver-builder/sowb-beaver-builder.js, js/slider/jquery.slider.js, widgets/google-map/js/js-map.js, widgets/image-grid/js/image-grid.js, widgets/simple-masonry/js/simple-masonry.js, widgets/video/js/so-video-widget.js
This change means we don't have to add a new function to compatibility JS every time we introduce a new widget. We just need to make sure all widgets add their setup functions to this event.
This will be especially useful as we introduce compatibility with more builders, which might require a similar late-setup system.
=> Introduced global `sowb_setup_widgets` event

widgets/contact/tpl/default.php
If Display Title is ticked but the contact title is empty the contact title will still be output. There's a reason to have the title not display, but there's no real reason to have the markup present if it's not being used.
=> Contact: Prevent empty title markup from being output

widgets/contact/contact.php
Display email along side name in the contact email. This will stop the question, "Where's the email?".
=> Contact: Display email after name

widgets/price-table/tpl/atom.php
This will allow users to use shortcode tooltip plugins while we currently don't have said functionality.
@gregpriday I ran do_shortcode before escaping the text as I suspect that might be better overall. With that said, should it be escaped before? I worry that a plugin might not escape the text at all and will end up trusting "bad" data.
=> Price Table: Shortcode support for feature text

widgets/testimonial/styles/default.less, widgets/testimonial/testimonial.php
The testimonial widget has a testimonial radius field mislabled as padding, I've changed it to Testimonial Radius.
The resulting funcitonality also doesn't work currently due to uising .border-radius() over .rounded()
=> Testimonial: Updated text radius label and fixed resulting functionality

base/inc/actions.php
It's a nice idea in concept but pages aren't publicly_queryable so it falls flat. 😞 
This might be related to #403, or rather, it might have been the change that exacerbated it.
=> Revert #379 - Link Field publicly_queryable check

widgets/testimonial/styles/default.less, widgets/testimonial/testimonial.php
If the user decides to have a large image size it can cause rather large display issues on tablet and mobile devices. This PR aims to fix that by offering responsive settings for image sizes so they can specificly set their desired mobile and tablet image sizes.
=> Testimonials: Add responsive image sizes

widgets/contact/contact.php
Added empty field check to prevent empty fields from overwriting valid fields (for example, two name fields). This will also prevent empty fields from being added to the email.
Changed the type validation to a single `switch()`.
=> Contact: Improved type Validation and added empty field check

widgets/headline/headline.php
In the current version the sub-headline new window setting is tied to the headline new window settings due to a typo.
=> Headline: Fixed type that tied subheadline new window to headline

base/inc/attachments.php, widgets/image/tpl/default.php, widgets/price-table/price-table.php
Resolves #234. This only applies to `<img>` tags and won't do anything for any places we're using the `background-image` style.
=> Added responsive image support where applicable.

base/inc/fields/color.class.php, base/inc/fields/text-input-base.class.php, base/js/admin.js
Resolves GH-180.
If a default color is set for a field, the 'Clear' button will become a 'Default' button and revert to the default color when clicked.
=> Set default color option in wpColorPicker.

base/css/admin.css, base/css/admin.less, base/inc/post-selector.php, base/js/posts-selector.js
Resolve #271.
This just adds the `multiple` attribute to the `select` element. We should consider using the generic form fields for the posts selector.
=> Allow multiple post types in posts selector field.

widgets/features/features.php
#427 
> A few user's have recently asked for the ability to add bullet lists to the feature's text and while it's possible, they have to use HTML. Changing this field to a TinyMCE field rather than a text field would make the whole process easier for people overall and give more control.
I see haven't seen any issues pop up as a result of this change. I've opted to not include shortcode support as I feel like at that point other widgets would be more suitable. Thoughts?
=> Features: Change text form field to a tinymce field

widgets/price-table/price-table.php
This will prevent a warning for when users don't add any features for a column.
> Warning: Invalid argument supplied for foreach() in D:\wamp\www\siteorigin\wp-content\plugins\so-widgets-bundle\widgets\price-table\price-table.php on line 206
=> Features: Prevent error when no features specified

widgets/taxonomy/taxonomy.php, widgets/taxonomy/tpl/default.php
This PR adds a text display setting for the taxonomy widget. This is ideal for when the user doesn't actually want to link to a specific page but instead purely wants to list them.
=> Taxonomy Display Setting: Text

widgets/button/button.php
Hello!
For a site I'm building I wanted to streamline the options the site owners had, so I unhooked some of the design options for buttons. This worked, but on load they threw errors because they where not set (But viewing them still worked). So I figured I'd fix that and create a pull request.
My first formal pull request to an open source project, so please tell me if something should've been done differently.
=> Allow design options to be unset without errors on save.

widgets/features/tpl/default.php
With the text field now being a TinyMCE field, these paragraphs cause a markup issue.
=> Features: Remove redundant paragraph from template

widgets/post-carousel/css/style.less
Due to the generic nature of the `.overlay` class, themes (and plugins) can quite easily unintentionally interfere with the Post Carousel due to the `.overlay` selector. By applying `position: static`; to the overlay, we should be able to avoid the conflict.
=> Carousel: apply static position on .overlay

widgets/layout-slider/layout-slider.php
Certain slides will look better if the user has the option of tiling the background rather than setting it to cover.
=> Layout Slider: Add ability to set Background Image to Title

widgets/contact/contact.php
This should resolve the vast majority of email related issues with the contact form, but there may be a few issues still present due to the possibility of the admin email being at a different domain.
=> Contact: add reply-to header

widgets/accordion/accordion.php
This will change the accordion repeater label title based on the item title.
Before:
After:
=> Accordion: Add Repeator Label Title

widgets/contact/contact.php
Currently, the To Email Address field doesn't mention that you can send to multiple emails by separating the emails with a comma. This PR corrects that.
=> Contact: mention it's possible to send to multiple emails

widgets/social-media-buttons/tpl/default.php
This PR will allow for the SiteOrigin Social Media Buttons to comply with [WCAG 2.4.4](https://www.w3.org/TR/UNDERSTANDING-WCAG20/navigation-mechanisms-refs.html) by using [ARIA8](https://www.w3.org/TR/WCAG20-TECHS/ARIA8.html). Tested using [WAVE](http://wave.webaim.org/).
=> Social Media Buttons Widget: Comply with WCAG 2.4.4

widgets/hero/hero.php
This PR will allow for shortcodes to work in the SiteOrigin Hero widget editor.
[Slack Reference](https://siteorigin.slack.com/archives/C02SYBBH2/p1509941695000013)
=> Hero: Add support for shortcodes

widgets/features/features.php, widgets/features/styles/default.less
Replaces #372. Resolves #298
This PR adds a global widget setting that adds the ability to control the features breakpoint. If SiteOrigin Page Builder is installed, it'll default to the global mobile breakpoint but the global widget setting is still present if the user wishes to override the Page Builder setting for the features widgets.
=> Features: Add ability to control responsive breakpoint

widgets/hero/styles/default.less
When there are either a lot of buttons added or there's more than one on mobile (and they're above normal width), the buttons will touch. This PR avoids this by adding a small amount of top margin.
Overflow of buttons example:
Big button mobile example:
=> Hero: Add margin-top to .so-widget-sow-button for spacing

widgets/accordion/styles/default.less
Resolves #617. This is a fixed version of #623.
Credit @acollis for the initial idea for this fix. This version escapes the calc to prevent less.js from processing the calc as math.
=> Accordion: Icon title collapse fix

base/inc/fields/tinymce.class.php
Replacement for #635
grunion_media_button is no longer run on the Widgets page ([reference](https://github.com/Automattic/jetpack/blame/5.6.1/modules/contact-form/grunion-editor-view.php#L18)) so there's no reason to do this anymore. It's been long enough that this shouldn't affect users as it's been several months.
=> Editor: stop removing grunion_media_button on widgets page

base/inc/post-selector.php
This prevents an issue where the most recent post will be excluded from a post carousel on a non-singular page such as a WooCommerce shop page (which is an archive), or category page.
=> Post Selector: Only exclude current post if page is singular

base/inc/widgets/base-slider.class.php
https://webkit.org/blog/6784/new-video-policies-for-ios/
> On iPhone, <video playsinline> elements will now be allowed to play inline, and will not automatically enter fullscreen mode when playback begins.
Basically, it allows for the autoplay to work more consistently on newer versions of iOS
=> Slider: Add playsinline for Video backgrounds for iOS

widgets/contact/styles/default.less
This PR will ensure the button doesn't appear with the default theme styling by using the button background color defined in the settings.
=> Contact: When Gradient disabled, set basic background

widgets/features/features.php, widgets/features/styles/default.less, widgets/features/tpl/default.php
This fixes an overflow issue on full width stretched features widgets. This issue only occurs in themes that don't hide overflow on their theme/content container.
[Related thread](https://wordpress.org/support/topic/page-width-exceeds/#post-9913254)
=> Features: Better feature padding removal on row ends

base/inc/widgets/base-slider.class.php
Similiar to #595 
This PR will allow for the SiteOrigin Slider to comply with [WCAG 2.4.4](https://www.w3.org/TR/UNDERSTANDING-WCAG20/navigation-mechanisms-refs.html) by using [ARIA8](https://www.w3.org/TR/WCAG20-TECHS/ARIA8.html). At least the base slider will comply. The contents may not comply but that's due to the selected widgets. Tested using [WAVE](http://wave.webaim.org/).
=> Sliders: WCAG 2.4.4

base/inc/fields/date-range.class.php, widgets/contact/contact.php
There are two different instances of From with two different meanings. This PR will provide context to translators.
[Reported here](https://wordpress.org/support/topic/dont-share-same-string-for-different-purpose/)
=> Translation: Add context to From strings

widgets/hero/hero.php, widgets/hero/styles/default.less
This PR adds responsive height settings for the hero widget. The breakpoint is controlled via the global widget settings.
=> Hero: Add responsive height settings

widgets/features/styles/default.less
Follow up to #651 
Certain users were having issues with the columns placement resizing and ended up with weird column placement. This PR also prevents the feature item spacing from being applied on mobile.
=> Features: item float clearing and padding mobile specific

widgets/features/styles/default.less
This prevents alignment issues with the icon in left/right positioned feature when the features widget is set to use a single column.
[Here's a test layout](https://drive.google.com/a/siteorigin.com/uc?id=1fUvUq735nR37kSnGLlMPji0X7BHkHPtg)
Before:
After:
=> Features: Don't set margin for one column left/right feature

widgets/button/styles/atom.less, widgets/button/styles/flat.less, widgets/button/styles/wire.less
This PR applies a max-width to ensure the button isn't cut off when users set a button width and it's smaller than the available width.
Reference gif:
=> Button: Add max-width to ensure buttons are responsive

widgets/contact/contact.php, widgets/contact/styles/default.less
Currently, the field height will apply to all fields which is normally okay but it looks odd if you pick a really small height as it'll also apply to the textarea. This change will add a dedicated height option for the textarea and it'll also prevent the standard field height from being applied to the textarea.
For example, here's an example of what it was like prior to this PR:
Now:
=> Contact textarea height

widgets/features/tpl/default.php
Even though you're given the ability to change the unit of measurement that the icon size uses, this change is disregarded as the icon sizing is locked to px. This PR fixes this.
=> Features: Allow icon size to use a different unit of measurement

widgets/price-table/styles/atom.less
Resolve #494
> Currently, on mobile devices, the equalize row functionality can result in really large amounts of scrolling of blank areas. As a result, we shouldn't try and equalize rows on mobile devices - basically, when the price table collapses.
This is a quick and simple fix.
=> Price Table: Disable equalized row heights on mobile

base/siteorigin-widget.class.php
Hello! We got a problem with using Page Builder in batch with Widgets bundle.
When widget has styles, it generates them once a week when the page is requested.
On this way, we got some middleware before user get the page. We have FCGI and CDN, those two tools cache pages and their static to make it faster for end user.
We trying to figure out how we could fix disappearing widget styles and that what we came to:
We add an option to make `*.css` file name generated with not unique hash everytime, but with sliced md5 of widget-id hash. You can check it here: `base/siteorigin-widget-class.php:1096`
=> Add condition get style hash by widget number

so-widgets-bundle.php
This PR prevents a fatal error from occurring if another plugin has already removed the editor link.
`HP Fatal error: Uncaught Error: Cannot unset string offsets in wp-content/plugins/so-widgets-bundle/so-widgets-bundle.php:745
`
[Related](https://siteorigin.com/thread/siteorigin-widgets-bundle-vs-wp-editor/)
=> Plugin Action Links: Check if edit link is present before removal

widgets/headline/headline.php, widgets/hero/hero.php
The current FitText Compressor setting doesn't outline that values above 1 are possible and what reducing (or increasing) does. This PR changes that.
=> Improve FitText Compressor Description

base/inc/widgets/base-slider.class.php, css/slider/slider.less
This CSS was added when autoplaying on mobile just wasn't possible so it was better just to up and hide the video.
@Misplon Can you please try this on iOS? I can confirm this is working on Android (for at least devices where autoplaying videos are possible)
=> Slider: don't hide video on mobile

compat/beaver-builder/styles.less
This PR adds dark styling for SiteOrigin Widget Bundle widgets. For reference, you can enable the dark mode by pressing o.
The follow-up commit styles the color picker button.
[Slack](https://siteorigin.slack.com/archives/C02SYBBH2/p1525076704000298)
=> Beaver Builder: Dark styling

base/siteorigin-widget.class.php
1. Hello, looks like I found a bug. When update widget, old css doesn’t deleted, because to delete_css function transferred `$new_instance` data not old one. Could you check this please ?
2. Also I have one question. Do you have a way to disable clear_file_cache() method ?
=> Remove old style after update widget

base/siteorigin-widget.class.php
[Slack](https://siteorigin.slack.com/archives/C02SYBBH2/p1535963127000100)
=> Widget CSS: Use inline CSS as a fallback if siteorigin-widgets directory or CSS file wasn't able to be created

widgets/features/features.php
A number of users have asked why the text doesn't appear inside of the container and while that would be nice, that's not what the container currently is - they're Icon Container. This PR will rename the setting labels to state that.
=> Features: Rename container settings

widgets/image/tpl/default.php
If no alt text is supplied for an image widget add an empty alt
attribute (alt="") for WCAG compliance. Nearly all images should have an
alt attribute to meet WCAG 2.1 Level A.
See
https://www.w3.org/WAI/WCAG21/Techniques/failures/F38
"This describes a failure condition for text alternatives for images
that should be ignored by AT. If there is no alt attribute at all
assistive technologies are not able to ignore the non-text content. The
alt attribute must be provided and have a null value (i.e., alt="" ) to
avoid a failure of this Success Criterion."
and
https://webaim.org/techniques/alttext/
"Every image must have an alt attribute. This is a requirement of HTML
standard (with perhaps a few exceptions in HTML5). Images without an alt
attribute are likely inaccessible. In some cases, …
=> Image widget - if no alt text is supplied add an empty alt attribute

widgets/contact/styles/default.less
On Android devices,  the checkboxes and radios form types are oddly aligned when multiple items are present due to the top margin applied to each option.
This cannot be replicated using Device Mode in DevTools and will only occur on mobile.
This PR will fix this issue and prevent it from happening again regardless of device. There will be a slight movement in the radio/checkbox placement as they are now veritically aligned with the label text.
=> Contact: Fix checkboxes and radio alignment on android

js/sow.jquery.fittext.js
This PR will set a minimum font size for FitText. This will prevent cases where the user ends up with text unreadable (without zoom) due to it being set sub 12px. The specific reason I've set it to 12px due to [the Google recommendation](https://developers.google.com/web/tools/lighthouse/audits/font-sizes).
=> FitText: Set minimum font size to ensure readability

widgets/layout-slider/layout-slider.php
This PR removes the `is_admin()` check from the Layout Slider widget. This check prevents the form from displaying in the SiteOrigin Widgets block. During testing, I wasn't able to find any issues with removing it. With that said, if you have a replacement you would like to be used, let me know and I'll add that.
=> SiteOrigin Widgets block: Fix Layout Slider not being editable

widgets/accordion/js/accordion.js
This PR prevents a history state being pushed on load when no hash is present.
Before:
After:
=> Accordion: Prevent history state from being pushed on load when no hash is present

widgets/accordion/accordion.php, widgets/accordion/js/accordion.js
This PR prevents the need for unique titles. Previously, if you used the same title in more than one place, all instances of that title would opened upon clicking one. This PR ensues the anchors are unique by appending the array index id if the title isn't unique.
This PR also prevents an instance where a partial match title won't open cause other titles to open - opening the `Other Example` item won't open `Example`.
=> Accordion: account for duplicate accordion titles

widgets/headline/headline.php, widgets/hero/hero.php
The higher the value, the more the text is scaled.
Example:
The first paragraph is 0.50
The second Paragraph is 0.75
The third Paragraph is 1.25
=> FitText Description Typo Correction

widgets/features/styles/default.less
Before:
After:
It's possible to replicate this issue by not adding multiple paragraphs of text or by adding something that doesn't add a paragraph (like a list).
[Test Layout](https://drive.google.com/a/siteorigin.com/uc?id=1i_yvMOud1Ll_kgWaO2nEnuvBfia0FhUV)
=> Features: Change selector to target .textwidget rather than p specifically

widgets/accordion/js/accordion.js
Accordion items with number titles will instantly close on open due to a type difference.
[Test layout here](https://drive.google.com/a/siteorigin.com/uc?id=1RL6D0R7rdW66hYffXylJQI2vF9iKV6eM)
=> Accordion - Resolve issue with number titles instantly closing upon opening a panel

widgets/post-carousel/js/carousel.js
Resolve #133.
This will allow for faster posts loading as the carousel won't wait until only a single post is visible before attempting to load new posts.
=> Post carousel - load new posts based on possible number of visible posts

widgets/features/styles/default.less
This PR will remove flex from each feature on mobile to prevent text from being (horizontally) cut off on mobile. This change will only apply when the user has the features widget to be enabled.
Before:
After:
[Test layout](https://drive.google.com/a/siteorigin.com/uc?id=1bQAhYEq1fkgmOCIqgqbNzZiTM98awPUJ).
=> Features: Remove flex from each feature on mobile

widgets/accordion/styles/default.less
Before:
After:
[Test Layout](https://drive.google.com/a/siteorigin.com/uc?id=1k_Wmr7xg_1BdyF2mShAg-yTvOrQPgnUf)
=> Accordion: Account for Open/close icon location being set to Left in Title Spacing

widgets/social-media-buttons/tpl/default.php
This PR resolves an issue on Android devices using Chrome. If the **Open in new window** setting is enabled, clicking a phone network button on an Android device, Chrome will open a new tab but not open the phone app. It appears there's a general issue with using `noopener noreferrer` alongside `target="_blank". Without them, it works without issue.
I tested this PR on a Pixel 2 XL and an iPhone 7 and saw no issues as a result of making this change.
=> Social Media Buttons: Prevent the Phone Network from Opening in a new window

widgets/google-map/google-map.php
This PR resolves an issue with the **draggable** and **scroll_zoom** setting migration code that results in it constantly running. This results in  the **Gesture Handling** being reset to **Greedy** upon viewing/opening the widget.
=> Google Maps: Detect draggable or scroll_zoom before running setting migration

widgets/hero/hero.php
Resolves #453.
The objective of this PR is to let users know that the Heading Size setting will set h1 and that h2-h6 font size will be based on this value. I can't let users know what the scale is because I don't think there is a consistent scale in use:
```
h1 {
font-size: @heading_size;
}
h2 {
font-size: @heading_size * 0.85;
}
h3 {
font-size: @heading_size * 0.7;
}
h4 {
font-size: @heading_size * 0.6;
}
h5 {
font-size: @heading_size * 0.5;
}
h6 {
font-size: @heading_size * 0.4;
}
```
=> Added a description for the Hero Heading Size

css/slider/slider.less
This PR adds padding around the slider navigation arrows to hopefully, make them a little easier to select.
@braamgenis Are you happy with the selector the padding has been added to and the negative margin to maintain the arrow position? Should we rather use ems?
Which CSS property order convention are we using? [Outside In](https://webdesign.tutsplus.com/articles/outside-in-ordering-css-properties-by-importance--cms-21685)?
Resolves #445.
=> Added padding to slider navigation arrows

widgets/contact/contact.php
At one stage we released a layout that had the support@siteorigin.com as the To Email Address. This has been fixed but there are still a few users who're using the older version with our email. Unfortunately, we also didn't enable any anti-spam features with the base layout.
This PR excludes support@siteorigin.com from being used as a To Email Address to hopefully reduce the amount of spam we're getting.
=> Contact Form: Prevent SiteOrigin Support email from being used as a To Email Address

base/inc/fields/css/date-range-field.less
The fixed width label size currently used causes translated strings to overflow and run behind the date field.
=> Changed the date range label width to `min-width`

widgets/contact/contact.php
A User emailed us and was confused why the Subject field wasn't respecting the Required setting. Turns out they had said a Default Subject set so that was being used when the user didn't input a subject. This, in hindsight, makes sense but it isn't mentioned anywhere. This PR will add a note to the Default Subject description to make this more apparent.
=> Contact: Add note to Default Subject about overriding Subject field types set to required.

admin/admin.js, widgets/google-map/fields/location.class.php
This PR adds a method of auto opening a widget settings modal, and implements that feature into the Google Maps widget form.
Resolves https://github.com/siteorigin/so-widgets-bundle/issues/898
=> Auto open Google Maps settings modal

widgets/features/features.php
The SiteOrigin Features Widget Container Position Icon Horizontal options control the container position while the top and bottom settings affect the icon placement. This is problematic as left actually means right and right means left. This PR will swap the left and right values,  but will still internally refer to them as the left and right for backwards compatibility.
=> SO Features: Container Position: Swap Right and Left values

base/css/admin.less
The new admin styles set a max-width which we weren’t accounting for in the widget select field styles.
Resolves https://github.com/siteorigin/so-widgets-bundle/issues/931.
=> Unset widget selection input max-width

base/inc/fields/css/media-field.less
* Falling back on core input field styling.
Resolves external media field height incorrect after WP 5.3.
=> Removed media fallback field padding

base/inc/fields/css/media-field.less
=> Ensure correct alignment of Pixabay search button

widgets/contact/contact.php
Currently, dev emails are replaced when the mail is sent. For consitency, we should replace it before then.
=> Contact: Check from field for dev emails and replace it

widgets/simple-masonry/tpl/default.php
This PR resolves #942 by giving each SiteOrigin Simple Masonry Image image the .sow-masonry-grid-image class. I also tested Litespeed Cache to ensure this would be enough to exclude the image from the Lazy Load and it was.
Be sure to exclude the proceeding period for the class during testing.
=> Add .sow-masonry-grid-image class to Simple Masonry Images

widgets/image-grid/image-grid.php
Resolves #910
Related #945
I used sow-image-grid-image_html instead of sow-image-grid-image due to that being using as a container. `image_html` was used due to it being the array key of where the image HTML is stored prior to output.
=> Add class to each Image Grid image

base/inc/fields/css/media-field.less
When the Block Editor is under about 690px in width, the external URL field collapses.
I'm not sure how to detect the width of the Block Editor with CSS to set breakpoints for different behavior so I've just switched the margin from the external URL field to the media field. If you have any better ideas, let me know. I think this is sufficient but I am open to ideas.
=> Switch media field and external URL margin

base/css/admin.less
=> Specify label styling

base/css/admin.less
The section heading alignment relies on a line-height that changes in the Block Editor. The result is seen below.
By stating the line height we're expecting in the Classic Editor we can fix this.
@AlexGStapleton Is `.siteorigin-widget-field-type-widget` used in Beaver Builder? I've only tested this targeting `.siteorigin-widget-field-type-section`. Can you test this PR in BB?
=> Added line-height to section heading

base/inc/fields/css/media-field.less
The media button styling is currently slightly broken in the Block Editor:
Below is how the button looks in the Classic Editor:
This PR aims to resolve this problem. From my testing, it seems to without issue.
=> BE fix media button

base/inc/attachments.php, widgets/slider/slider.php
This PR will allow users to exclude the SiteOrigin Slider slide images from lazy load plugins. This was directly in response to a report about a display issue the SiteOrigin Slider widget has with the Jetpack Lazy Load.
This PR also extends the `siteorigin_widgets_get_attachment_image` function by adding a `class` parameter that allows developers to easily give images a class.
=> Slider: Add class to slide images

widgets/accordion/js/accordion.js
This PR prevents potential visability issues if the user is nesting accodions inside of an accordion that's not open by default.
=> Accordion: When hiding panels, only search current accordion and not nested accordions

base/inc/fields/icon.class.php, icons/icons.php
I'm currently adding fontawesome pro to this field. And I'm removing other font available to the user. So if fontawesome doesn't exist in the array, my custom font was not rendering.
Tested on debian and php 7.2
=> Use first element in $widget_icon_families instead of raw string.

base/inc/widgets/base-slider.class.php
Related #747.
This PR prevents the output of the slide numbers to prevent an issue where they'll appear in post excerpts. Previously, it was argued that these slide numbers should be retained for accessibility reasons but there's already `aira-label` in place which is sufficient for accessibility. The previously decided solution was to implement functionality that automatically generates an excerpt from the first SiteOrigin Editor widget. While useful, we've run into situations where an editor isn't being used.
=> Remove slider slide number from output

js/jquery.touchSwipe.js
Resolves #999.
The updated version now allows for Windows computers with touchscreens to work and the amount of scroll required to proceed has been slightly reduced. Unfortunately, you're still unable to scroll vertically after touching and holding an item and I wasn't able to find any PR that resolved that. We'll likely need to switch a different library or fork that one to resolve that. Overall, the improvements in the newer version are still worth updating for.
I tested the updated version on Windows, Android, and iPad (I don't currently have an iPhone on hand).
=> Update jquery.touchSwipe.js (SO Post Carousel)

base/js/admin.js, widgets/simple-masonry/simple-masonry.php
Implemented fallback system for masonry form item labels where the Wordpress media tag will be used as the item label when the form's title field is not populated.
=> #924: Change item label to image title if item

widgets/editor/editor.php
The PHP Notice message in #994 is coming from the situation where the get_post() function returns a null value. This happens under two conditions:
1. The post is previewed before it has been saved for the first time, immediately after creation.
2. Every time the TinyMCE editor's preview function is used.
To resolve this I have simple wrapped the return of the get_post() function in a null check.
The $post->ID is still used later on in the code and may give a similar message. However, since this only applies to Classic Editor pages, that have "more" link functionality, I suspect that all pages hitting that code would already be saved and that the error will therefore not occur. I have, at least, not been able to reproduce the error with widgets in the Classic Editor. Since it only shows up …
=> #994: Fixed PHP Notice on Editor Widget previews.

widgets/accordion/accordion.php, widgets/button/button.php, widgets/contact/contact.php, widgets/cta/cta.php, widgets/editor/editor.php, widgets/features/features.php, widgets/google-map/google-map.php, widgets/headline/headline.php, widgets/icon/icon.php, widgets/image-grid/image-grid.php, widgets/image/image.php, widgets/post-carousel/post-carousel.php, widgets/price-table/price-table.php, widgets/simple-masonry/simple-masonry.php, widgets/slider/slider.php, widgets/social-media-buttons/social-media-buttons.php, widgets/tabs/tabs.php, widgets/taxonomy/taxonomy.php, widgets/testimonial/testimonial.php, widgets/video/video.php
Unlike what was described in #885, I was able to find all of the Widget descriptions in the POT file. The problem was that most widgets had two descriptions:
1. The PHP comment description, which is used to describe widget in the Page Builder editor.
2. The description in the post options array in the constructor that is sent to the parent constructor, which is used to describe widgets in the Wordpress Appearance/Widgets screen.
I was surprised to see that the POT file generator picks up the PHP comment description, and I have confirmed that the translations all work perfectly on that value.
The problem that I encountered when trying to test this issue was that the number 1 and number 2 descriptions from the list above were usually different. I would create a translation for what looked …
=> #885: Improved reliability of widget description translations.

css/slider/slider.less
Resolves #1005.
Pagination spacing relies on the extra space created between inline-block elements. If a user enables HTML optimization in a plugin like AO those spaces will be removed when the HTML is minimized and the new lines are removed.
It isn’t necessary to reset the font size for the list items but I did it anyway.
According to this page https://stackoverflow.com/questions/5078239/how-do-i-remove-the-space-between-inline-block-elements the method I’ve used is compatible as follows:
This works in recent versions of all modern browsers. It works in IE8. It does not work in Safari 5, but it does work in Safari 6. Safari 5 is nearly a dead browser (0.33%, August 2015).
Another option would be to format our HTML so that each list item for the pagination is on the same line.
=> Prevent pagination inline-block element spaces

base/base.php, base/inc/fields/icon.class.php
While trying to create [this plugin](https://github.com/ridgekuhn/so-widgets-icon-fap) which adds Font Awesome Pro support, I ran into the issue described here: https://siteorigin.com/thread/getting-a-custom-icon-to-save-in-icon-widget/
The `siteorigin_widgets_icon_families` filter hook is flexible enough to let you add an array of styles to `$icon_families['my_icons']['styles']`, and will create the dropdown menu in the widget for you, etc; but when `SiteOrigin_Widget_Field_Icon::get_value_parts()` tries to get the value parts to save or render the widget, it's hard-coded to look for a style key beginning with `sow-fa*`, instead of the style keys that were stored in `$icon_families['my_icons']['styles']` in the filter hook. 
This pull request adds a …
=> Add support for custom icon styles

base/inc/fields/css/media-field.less
To replicate this issue, insert a Simple Masonry widget and insert an image with a long title. Next, carefully hover over the thumbnail in the media field, notice the scrollbar.
This PR prevents the scrollbar from appearing.
=> Prevent media field overflow

widgets/simple-masonry/js/simple-masonry.js, widgets/simple-masonry/simple-masonry.php, widgets/simple-masonry/styles/default.less, widgets/simple-masonry/tpl/default.php
Resolve https://github.com/siteorigin/so-widgets-bundle/issues/1023
This PR adds a preloader to the Simple Masonry widget. This prevents an issue where the images display at full size before they've finished loading and then are resized into a Masonry.
Note: you'll need to clear wp-content/uploads/siteorigin-widgets or create a new widget due to the CSS cache not being cleared when plugin files are manually replaced.
=> Simple Masonry Preloader

base/css/admin.less
Currently, the repeater remove icon hover looks as follows:
Note the alignment, it's correct. This PR corrects that issue. I'm not seeing any negatives from this change, can you, Alex?
=> Changed widget remove icon v-align to baseline

widgets/testimonial/css/style.less, widgets/testimonial/styles/default.less, widgets/testimonial/testimonial.php
Resolve #1035
This PR will prevent an issue where larger Testimonials on the previous row can cause alignment issues on the next. It will also stretch the testimonials so that they're all same height.
Here's a screenshot of this issue:
I had meant to split this commit into two but I had already gone too deep before I did. 😞
=> Testimonial: Resolve Alignment issues and stretch testimonials

widgets/post-carousel/post-carousel.php
This will prevent all posts from outputting. 10 will be output at a time instead.
=> Post Carousel: Remove default widget specific Posts Per Page

widgets/simple-masonry/js/simple-masonry.js, widgets/simple-masonry/simple-masonry.php, widgets/simple-masonry/tpl/default.php
This PR resolves https://github.com/siteorigin/so-widgets-bundle/issues/1049. It requires https://github.com/siteorigin/so-widgets-bundle/pull/1050.
This PR implements [this Packery option](https://packery.metafizzy.co/options.html#originleft). 
The setting is internally known as layout_origin_left as the value needs to be a boolean and layouts_origin = true/false makes less sense than layouts_origin_left = true/false. While this setting could logically be a checkbox, I agree with the idea of using a select as it's more approachable and obvious what the outcome will be.
=> Simple Masonry: Add Layout Origin setting

widgets/features/styles/default.less
Resolve https://github.com/siteorigin/so-widgets-bundle/issues/1074
Removing this CSS allows for the icon and text to convert each other when sizing. This means that the features text may be slightly smaller as a result of this change due to the icon pushing it over.
=> Features: Prevent Text Overlapping Icon

widgets/post-carousel/js/carousel.js
The const usage was resulting in a JavaScript error in IE 11.
=> Post Carousel: IE 11 Fix

widgets/tabs/js/tabs.js
This PR ensure feature parity with the Accordion widgets by replicating [scrollToPanel](https://github.com/siteorigin/so-widgets-bundle/blob/1.17.0/widgets/accordion/js/accordion.js#L22-L32) functionality. scrollToTab allows for users to link to specific tabs and have the Tabs widget scroll to them like a standard Page Jump would (albeit with a nice scrolling effect).
Previously if the user linked to a tab the tab would change, but the browser would not scroll to the tab.
=> Tabs: Ensure Tabs are in view if anchor set and on hashchange

widgets/image/image.php
Related https://github.com/siteorigin/so-widgets-bundle/pull/1054
This PR adds `siteorigin_widgets_image_args` to the SiteOrigin Image Widget. This filter allows you to adjust _all_ of the image widgets' arguments and attributes. The previous filter, `siteorigin_widgets_image_attr, is effectively deprecated by this but that filter is still retained for backward compatibility.
Test code:
```
add_filter( 'siteorigin_widgets_image_args', function( $args ) {
$args['attributes']['title'] = 'This title has been overriden';
return $args;
} );
```
=> Image widget: Add siteorigin_widgets_image_args filter

base/inc/fields/code.class.php
Resolve https://github.com/siteorigin/so-widgets-bundle/issues/1060 
This will remove the standard HTML sanitization from occurring. It does not affect sanitization elsewhere but that sanitization isn't interesting with the code form field. Developers using this form field would already be escaping on output so backwards compatibility isn't an issue.
=> Code form field: Remove Sanitization

widgets/post-carousel/css/style.less, widgets/post-carousel/tpl/base.php
@AlexGStapleton The goal of this PR is to better vertically align the carousel nav buttons when a title is present. 
Request: https://wordpress.org/support/topic/post-carousel-in-1-17/page/2/#post-13038229
As far as I'm aware, within CSS3, we don't have a way of counting children and then applying styles to the parent based on the count. Ideally, I'd apply Flexbox when two children are present within the `.sow-carousel-title` div (the title and the nav container). Counting in this manner will be included in CSS4.
I've set this PR to draft status. Let me know if you'd prefer to go in another direction.
=> Vertically align Post Carousel nav buttons if a title is present

widgets/hero/hero.php
This PR ensures that the Hero widget buttons aren't loaded unless [buttons] is added to the Hero frame content. This PR will indirectly prevent the Hero widget from being affected by https://github.com/siteorigin/so-widgets-bundle/issues/1077.
[Related](https://github.com/siteorigin/so-widgets-bundle/pull/1073#discussion_r449801433).
=> Hero: Don't load buttons unless set to output

widgets/editor/editor.php
This issue resolves https://github.com/siteorigin/siteorigin-panels/issues/770. This issue is caused due to the Block Editor automatically altering all links with targets to include `noreferrer`. This is problematic as the Block Editor will reject a widget if the markup of a block changes enough. 
It should be noted that `noreferrer` isn't added automatically when using the link builder. This is due to a known WP Issue and it's unlikely ever to be fixed as `noreferrer` will likely be removed in WordPress 5.5 ([related](https://core.trac.wordpress.org/ticket/49558)).
For this code to be run the user will need to recover the widget and make a minor change to the editor widget. The user can recover the widget by clicking the three vertical dots and clicking the recovery link.
=> Editor: Add noreferrer to any target links

widgets/post-carousel/js/carousel.js
This PR checks if the number of visible items is larger than the total number of posts on load and after a resize.
=> Post Carousel: Disable scroll if number of visible posts is more than total posts

widgets/button/styles/atom.less, widgets/button/styles/flat.less, widgets/button/styles/wire.less
This PR resolves an issue where the button will use the hover color by default.
=> Button: Don't adjust :visited color

widgets/contact/tpl/default.php
This PR resolves https://github.com/siteorigin/so-widgets-bundle/issues/1028.
Neither `wp_kses_post` nor `wpautop` are required here as they're already [run when the page saves](https://github.com/siteorigin/so-widgets-bundle/blob/e0deee4e80c6c27a5e944e22f814a7443569b389/base/inc/fields/tinymce.class.php#L504-L516).
=> Contact: Don't double sanitize success message

widgets/slider/slider.php
Resolve https://github.com/siteorigin/so-widgets-bundle/issues/1120
In [WordPress 5.5 Lazy Loading](https://make.wordpress.org/core/2020/07/14/lazy-loading-images-in-5-5/) was introduced. Cycle2 doesn't appear to handle the new lazy load very well as the image is never actually loaded, nor are any related image load events are triggered (for example, [this one](https://github.com/siteorigin/so-widgets-bundle/blob/1.17.4/js/slider/jquery.slider.js#L255-L262)) - at least in Firefox. This PR disables the new loaded attribute for the SiteOrign Slider widget to avoid this.
=> SiteOrigin Slider: Disable 5.5 Lazy Loading

js/slider/jquery.slider.js
Images added to the Hero/Layout Slider contents will prevent the Hero and Layout Slider from showing due to the 5.5 lazy load. To be clear, it's not the slide background image, it's a separate image added to the slide content. 
Previously, we would preload all of the images added to the slider, but that doesn't actually appear to be intentional and looks to be more of an oversight that wasn't corrected with the introduction of the Hero and Layout Slider widgets.
=> Slider: Only Preload Slide Images

widgets/slider/slider.php
Contrary to what is [said here](https://make.wordpress.org/core/2020/07/14/lazy-loading-images-in-5-5/) (screenshot below), `lazy` needs to actually be set to `true` to be disabled. This is due to [this line](https://core.trac.wordpress.org/browser/tags/5.5/src/wp-includes/media.php#L1053) unsetting the lazy attribute if it's set to false when the lazy attribute needs to be output.
=> DIsable Lazy Loading for SO Slider widgets added to Block Editor

widgets/post-carousel/js/carousel.js
Resolve https://github.com/siteorigin/so-widgets-bundle/issues/1122
A custom Slick Go to Function was implemented to avoid https://github.com/kenwheeler/slick/issues/1006.
=> Post Carousel: Prevent Blank Slides after all posts are loaded

admin/admin.js
This PR prevents the [Enable jQuery Migrate Helper](https://wordpress.org/plugins/enable-jquery-migrate-helper/) plugin from showing a notice when viewing **WP Admin > Plugins > SiteOrigin Widgets**. This change isn't directly required, but this will avoid any reports.
To verify the settings form is still working as intended please navigate to**WP Admin > Plugins > SiteOrigin Widgets** and open a any widgets settings. Make a change, save, and then reload the page. Check the settings to ensure your change was saved.
=> Widget Settings: Avoid jQuery migrate notice by using $.get()

widgets/post-carousel/css/style.less, widgets/post-carousel/js/carousel.js, widgets/post-carousel/styles/default.less, widgets/post-carousel/tpl/carousel-post-loop.php
Resolve https://github.com/siteorigin/so-widgets-bundle/issues/1108
- The first item is the default tab index.
- Upon tabbing to tab index slide, use left and right keyboard arrows to navigate to the next/previous item
- The tab index is the currently active item
- Add keyboard navigation for post carousel arrows by pressing Enter or Space. Will navigate entire carousel slides rather than item by item.
`build:dev` is required due to LESS changes.
=> Post Carousel: Add Keyboard Navigation

base/css/admin.less
[Suggested here](https://github.com/siteorigin/so-widgets-bundle/pull/1131#issuecomment-682106511)
This PR will bold the Post Query settings group label. This is so it's consistent with section 
labels.
=> Bold Post Query settings group label

base/siteorigin-widget.class.php
Resolve https://github.com/siteorigin/so-widgets-bundle/issues/1085
This PR resolves the sub widget preview issue by only outputting widget CSS inline during if the preview is the direct widget preview - the dedicated preview widget button. A conditional is added rather than completely removing this line to allow for the widget preview button to still render as expected.
[Test widget](https://drive.google.com/uc?id=1vinLmiM6-LgEWOIiGXfdSDipd-hlAAg9). Once installed navigate to **WP Admin > plugins > SiteOrigin Widgets** and activate the Preview Error widget. Add it to a Block Editor page and then set a text color, and preview the widget. As expected, the color won't change. Load this PR and make any change to the widget (to trigger the content preview update) and then preview the widget …
=> Only output widget CSS inline during if preview is full widget

widgets/image/styles/default.less
Resolve https://github.com/siteorigin/so-widgets-bundle/issues/1141
Before:
After:
=> IE 11: Prevent images from exceeding widget container

compat/beaver-builder/beaver-builder.php
This PR removes our usage of wpColorPickerL10n if the version of WordPress being used is at least 5.5. No replacement is required for any WP version after 5.5 as the translations are handled directly by the color picker ([reference](https://core.trac.wordpress.org/ticket/50596)). [We may still get flagged](https://wptavern.com/wordpress-5-5-1-released-with-backfill-for-deprecated-javascript-globals) for using wpColorPickerL10n, but it's not actively being used and only present for backwards compatibility.
=> Don't use wpColorPickerL10n if WP >= 5.5

base/inc/fields/js/tinymce-field.js
[Resolve the issue highlighted here](https://github.com/siteorigin/so-widgets-bundle/issues/745#issuecomment-689679515). You can test this PR by downloading [their widget](https://github.com/siteorigin/so-widgets-bundle/issues/745#issuecomment-667828328) (drop it into the SiteOrigin Widgets Bundle Widgets directory - their layout isn't required). To replicate it:
- Add a topic
- Add an item (no text required)
- Open Item
- Add a new topic
- Add an item to new topic
- Open the second item and TinyMCE won't appear.
There is a small chance of the id that's generated being a duplicate,. It's unlikely though due to how rare this issue is. It can be avoided by simply reloading the page.
=> Prevent TinyMCE not initializing in repeaters in repeaters

widgets/image/styles/default.less
Resolve https://github.com/siteorigin/so-widgets-bundle/issues/1152
This is done by applying the https://github.com/siteorigin/so-widgets-bundle/issues/1141 fix in a media query that only targets IE 11.
=> Image: Prevent image stretching while using Safari

compat/elementor/styles.less
-  Set default form text color (Resolve https://github.com/siteorigin/so-widgets-bundle/issues/1143)
- Prevent color picker button overlapping selected color and incorrect sizing. ([screenshot](https://i.imgur.com/2OQ9D4f.png))
- Prevent Noticeable lag when using the color picker. ([gif](https://i.imgur.com/23JpcDi.gif) - every time it moves is a single click)
- Move Color picker buttons and color field to the same line. ([screenshot](https://i.imgur.com/2OQ9D4f.png))
- Reduce size of measurement fields
=> Elementor styling changes

base/siteorigin-widget.class.php
Resolve https://github.com/siteorigin/so-widgets-bundle/issues/1149.
This is a follow up to https://github.com/siteorigin/so-widgets-bundle/pull/1127 so the following needs to be tested:
SiteOrigin Widget Block Preview
SiteOrigin Layout Block Preview
Block Editor Preview
Classic Editor Preview
Widget Preview (this is the dedicated widget button).
=> Ensure widget CSS is output inline if WB Preview

widgets/video/tpl/default.php
Resolves https://github.com/siteorigin/so-widgets-bundle/issues/1160
Adds `sow_video_autoplay_mute_self_hosted` that can be used to prevent the video from being muted. Here's an example snippet that does that:
`add_filter( 'sow_video_autoplay_mute_self_hosted', '__return_false' );`
=> Video Play: Mute Self Hosted Videos set to autoplay

base/inc/fields/js/tinymce-field.js, base/js/admin.js
This PR resolves an error that results in TinyMCE sometimes not working correctly. An example of this is with the Editor or Tabs widget.
Follow up to https://github.com/siteorigin/so-widgets-bundle/pull/1146
=> TinyMCE: Only Alter textarea id when field is added in repeater.

widgets/editor/tpl/default.php, widgets/image/tpl/default.php, widgets/price-table/tpl/atom.php, widgets/simple-masonry/tpl/default.php, widgets/social-media-buttons/tpl/default.php, widgets/testimonial/tpl/default.php, widgets/video/tpl/default.php
Resolve https://github.com/siteorigin/so-widgets-bundle/issues/913
Titles are already escaped [here](https://github.com/siteorigin/so-widgets-bundle/blob/1.17.8/base/inc/fields/text-input-base.class.php#L76-L80)
I tested using:
`<p>test</p><p>123</p><script>alert(123)</script>`
=> Allow HTML in widget title fields

base/inc/fields/number.class.php, base/inc/fields/text-input-base.class.php, widgets/headline/headline.php, widgets/hero/hero.php
Resolve https://github.com/siteorigin/so-widgets-bundle/issues/1174
Safari won't allow number field inputs with a decimal amount unless the field has a decimal step amount. I'm unsure if this is a bug, or intentional.
=> Add Number Step Option to resolve Safari bug

base/inc/fields/posts.class.php
Resolve https://github.com/siteorigin/so-widgets-bundle/issues/1173
You can test this by opening the Post Carousel field and finding:
```
'posts' => array(
'type' => 'posts',
'label' => __('Posts query', 'so-widgets-bundle'),
'hide' => true,
```
Add to the next line:
```
'fields' => array(
'posts_per_page' => array(
'label' => __( 'Example label', 'so-widgets-bundle' ),
),
'sticky' => array(
'remove' => true,
),
),
```
=> Post Form Field: Add ability to override default fields

widgets/post-carousel/js/carousel.js
This PR was done to avoid a potential situation where the load is triggered before setup_widgets is. It'll also avoid a situation where an error occurs if Slick isn't able to load.
=> Ensure Carousel is setup before triggering load event

build-config.js
This prevents *.min.min files that was resulting in weird minify issues in the Block Editor.
=> Build Config: Exclude already minified JS files

widgets/accordion/js/accordion.js
This PR brings the Accordion widget into line with how the Tabs widget handles scroll to. If the user is below the Accordion panel and opens a new one they will now be scrolled up. Previously, the scroll would only occur if the user was above it.
=> Accordion: Scroll to panel if the user is below it

base/base.php, base/siteorigin-widget.class.php, widgets/accordion/styles/default.less, widgets/button/button.php, widgets/button/styles/atom.less, widgets/button/styles/flat.less, widgets/button/styles/wire.less, widgets/contact/contact.php, widgets/contact/styles/default.less, widgets/cta/styles/default.less, widgets/features/features.php, widgets/features/styles/default.less, widgets/headline/headline.php, widgets/headline/styles/default.less, widgets/hero/hero.php, widgets/hero/styles/default.less, widgets/tabs/styles/default.less, widgets/testimonial/styles/default.less
Resolve https://github.com/siteorigin/so-widgets-bundle/issues/1179
`siteorigin_widgets_google_font_fields_X` has been removed, but as it's not the main method of adding fonts I don't see any harm in removing it.
=> Enqueue Google Fonts rather than @import

widgets/slider/slider.php
Resolve https://github.com/siteorigin/so-widgets-bundle/issues/1192
This PR will ensure we comply with HTML standards with how we're disabling (lazy) loading for the Slider images. I didn't notice any issues after making this change. Please be sure to test the SiteOrigin Layout block preview as that's why the [original change](https://github.com/siteorigin/so-widgets-bundle/pull/1125) was made.
=> Slider: Set Loading To Eager

js/sow.google-map.js
Resolve https://github.com/siteorigin/so-widgets-bundle/issues/1183
Once set up, maps can be accessed via `sowb.SiteOriginGoogleMapInstances`
=> Expose Maps Instance

widgets/contact/js/contact.js
The previous selector was invalid. This PR will ensure the Accordion widget is opened on load. 
To test this, add an Accordion widget with a SiteOrigin Contact Form inside one of the panels - ensure the panel is set to be closed by default. Fill out the form and then submit it. The Accordion panel will be opened on load.
=> Contact: Update Accordion Selector

widgets/google-map/styles/default.less
This will prevent theme CSS unintentionally overriding styling and causing readability issues.
=> Map Consent: Add Button and Link Styling

base/inc/string-utils.php
This PR accounts for nested arrays passed to the siteorigin_widgets_underscores_to_camel_case function.
An example use case are item labels. Standard Item labels use `value_method` to assign a function to retrieve the value. `value_method` is then converted to `valueMethod` by `siteorigin_widgets_underscores_to_camel_case` for use with JavaScript. This wasn't however possible in a `selectorArray` and required `valueMethod` to be used instead of `value_method`. This PR allows for both `value_method` and `valueMethod` to now be used.
You can test this PR by changing [this line](https://github.com/siteorigin/so-widgets-bundle/blob/1.17.8/widgets/simple-masonry/simple-masonry.php#L53) to value_method - requries https://github.com/siteorigin/so-widgets-bundle/pull/1198
=> Underscores to Camel Case: Account for nested arrays

base/inc/fields/js/media-field.js, base/inc/fields/media.class.php
This PR adds the .current title field to the media field. This field is used by widgets such as the Simple Masonry and Layout Slider to label the item based on the select time.
=> Add .current title to media field for item labels

widgets/image-grid/image-grid.php, widgets/image/image.php, widgets/simple-masonry/simple-masonry.php
Resolve https://github.com/siteorigin/siteorigin-premium/issues/437 (also adds it to Image Overlay).
- Supports image caption, title.
- Prevent filename being used as title
- Add filter `siteorigin_widgets_auto_title` to disable auto title.
Here are some filters to test the filter.
Disable auto title for all image widgets:
`add_filter( 'siteorigin_widgets_auto_title', '__return_false' );`
Disable auto title for image widget:
```
add_filter( 'siteorigin_widgets_auto_title', function ( $enabled, $widget ) {
if ( $widget == 'sow-image' ) {
return false;
}
return true;
}, 10, 2 );
```
=> Images widgets: Add auto image titles

widgets/tabs/js/tabs.js
This PR will prevent the scrollto setting from affecting the currently selected tab. Previously, selecting the currently selected tab when scrollto was disabled would still trigger the scroll.
=> Tabs: Prevent scrollto on selected tab

admin/admin.js, admin/trianglify.js, base/inc/fields/js/autocomplete-field.js, base/inc/fields/js/code-field.js, base/inc/fields/js/date-range-field.js, base/inc/fields/js/icon-field.js, base/inc/fields/js/media-field.js, base/inc/fields/js/multi-measurement-field.js, base/inc/fields/js/order-field.js, base/inc/fields/js/posts-field.js, base/inc/fields/js/presets-field.js, base/js/admin.js, compat/block-editor/widget-block.js, compat/visual-composer/sowb-vc-widget.js, js/jquery.cycle.js, js/lib/slick.js, js/slider/jquery.slider.js, js/sow.google-map.js, widgets/contact/js/contact.js, widgets/cta/js/cta.js, widgets/image-grid/js/image-grid.js, widgets/post-carousel/js/carousel.js, widgets/price-table/js/pricetable.js, widgets/simple-masonry/js/simple-masonry.js, widgets/tabs/js/tabs.js
PB PR (required): https://github.com/siteorigin/siteorigin-panels/pull/827
Any form fields that have been altered should be tested.
Widgets to test (the rest weren't altered):
Contact Form in Accordion and Tabs Widget (have panel set to close by default)
(please note https://github.com/siteorigin/so-widgets-bundle/pull/1207/files)
Image Grid (ensure alignment is maintained after resizing the window)
Post Carousel keyboard navigation
Notes:
- pikaday.js and Slick aren't using jQuery, and instead uses native JS (ignore blur(), and click()).
- After closing the Add Media window, "JQMIGRATE: jQuery.fn.undelegate() is deprecated" will be triggered by a WP script.
- Slick changes tracked here https://github.com/siteorigin/slick/pull/1
- Cycle2 changes tracked here …
=> 5.6 jquery migrate changes

base/inc/fields/font.class.php
Resolve https://github.com/siteorigin/so-widgets-bundle/issues/1236
You can test this by selecting an italic font and then saving. This PR ensures italic isn't cleared upon saving.
=> Sanitize italic fonts rather than clearing them

js/sow.google-map.js
This PR corrects the marker property names to use the correct camelCase format. They were previously using variable names weren't camelCase so after https://github.com/siteorigin/so-widgets-bundle/pull/1199 they broke.
This PR can be tested by giving a marker a custom icon and the icon won't show. Once the branch is enabled, the icon will show.
=> Google Maps: Correct Marker JS Property Names

base/inc/fields/measurement.class.php
This PR will allow developers to alter the measurements list when adding the form field to their widget. It'll also allow them to change the default unit of measurement to use when either the unit of measurement isn't able to be detected or it's been removed (due to not being in the measurement list).
=> Measurement: Add units and default_unit parameters

widgets/tabs/js/tabs.js
Tab version of https://github.com/siteorigin/so-widgets-bundle/pull/1213
This PR will result in external Tab Anchor links triggering the scroll to. It ignores the scroll to setting as the hashchange will only ever happen if the user is intentionally linking to the Tab.
=> Tabs: When hash change opens tab, scroll to it

widgets/post-carousel/js/carousel.js, widgets/post-carousel/post-carousel.php, widgets/post-carousel/tpl/base.php
This filter is used to limit the total posts returned by the widget.
Resolve https://github.com/siteorigin/so-widgets-bundle/issues/1210
This PR highlighted an issue introduced by https://github.com/siteorigin/so-widgets-bundle/pull/1171. The carousel was still factoring in the total number of visible items so it would sometimes skip to the last item - you can check this issue by setting the post limit to 12 and then removing [this commit](https://github.com/siteorigin/so-widgets-bundle/pull/1220/commits/96e68a6eeb244a44169e51baa6975c24c1804223).
Test Code:
```
add_filter( 'siteorigin_widgets_post_carousel_post_limit', function( $limit ) {
return 12;
} );
```
=> Post Carousel: Add siteorigin_widgets_post_carousel_post_limit filter

widgets/features/features.php
This PR resolves an issue that can occur if the features widget was created before the title tag was introduced. To test this, import the Consultent prebuilt layout and the notice will be added to the debug.log.
`[25-Dec-2020 11:31:19 UTC] PHP Warning:  Undefined array key "title_tag" in C:\Users\Alex S\Local Beta Sites\siteorigin\app\public\wp-content\plugins\so-widgets-bundle\widgets\features\features.php on line 303`
=> Features: Ensure title tag exists before using it

base/css/admin.less
This PR corrects the line-height and spacing of inputs. This corrects the alignment of the `link` and `measurement` field. It also makes inputs more consistent with the Classic Editor look.
=> Block Editor: Correct input line-height and padding

widgets/image/image.php
Requires https://github.com/siteorigin/so-widgets-bundle/pull/1243
Please note that if you revert this PR the image size will continue to be `custom_size` until you save the widget again.
=> Image widget: Add Support for Custom Image Size 

widgets/editor/editor.php
This PR will prevent the more tag from being processed in previews. When processed, it can cause issues with widget previews, and the SEO analysis due to the read more text being used over other text.
To test this issue create a post and add a SiteOrigin Editor widget. Add some text and then insert more text. Add some more text after the more quicktag and then preview the editor widget. You can also test this using the SiteOrigin Layout Block Preview, and content analysis word count.
=> Editor: Don't process more quicktag in previews

widgets/video/tpl/default.php
Resolve https://github.com/siteorigin/so-widgets-bundle/issues/1248
This PR will ensure the video when viewed on mobile Safari is able to play inline and doesn't force full screen ([related MDN](https://developer.mozilla.org/en-US/docs/Learn/Performance/video#video_autoplay)).
=> Video: If autoplay is enabled, add playsinline

widgets/image-grid/styles/default.less
This PR prevents undesired output due to whitespace being rendered by browsers. This happens due to how browsers output `display: inline-block;` and that doesn't happen when using flexbox. This unintended spacing can make it trickier to get the desired amount of spacing because the horizontal spacing will always be more than the vertical spacing.
To test:
- Add a series of images that you can easily tell the sides from (I used [this image](https://i.imgur.com/rdUR6n7.png))
- Set the Spacing to 0 
- Inspect resulting output
- Clear wp-content/uploads/siteorigin-widgets or make a design change to the Image Grid widget (this is required to regenerate the generated CSS stylesheet).
- Inspect resulting output
Before:
After:
=> Image Grid: Display Using Flexbox to Prevent Unintended Spacing

base/inc/fields/css/measurement-field.less
Related https://github.com/siteorigin/so-widgets-bundle/pull/1261#issuecomment-805142949
This PR ensures the measurement field is more consistently sized. It also prevents the unit from being clipped due to a smaller than intended line-height (this is visible in the linked comment).
This affects both the Block Editor and Classic Editor.
This PR is compatible with #1261.
=> Improve Measurement field spacing for more consistent field sizing/padding

base/css/admin.less
How it looks in the Block Editor prior to this PR.
How it normally looks in Classic Editor:
This CSS is from wp-admin/css/forms.min.css.
=> Twenty Twenty-One Block Editor: Restore Select Styling

widgets/editor/editor.php
This PR prevents the following notice:
`Notice: Undefined index: action in wp-content/plugins/so-widgets-bundle/widgets/editor/editor.php on line 117`
=> Editor: Prevent notice when checking if preview

base/inc/fields/css/image-size-field.less
This PR unbolds the custom image size inputs.
Before:
After:
=> Image Size: Don't bold custom size input

base/inc/fields/font.class.php
This is a follow up to https://github.com/siteorigin/so-widgets-bundle/pull/1237. That PR relied on a number always being present before italic, but that doesn't always happen. This PR will allow for all possible variant formats. For example:
Alegreya:italic
Alegreya:500
Alegreya:500italic
=> Font: Allow italic variant with no font weight

widgets/post-carousel/js/carousel.js
Due to https://github.com/siteorigin/so-widgets-bundle/pull/1220, there's a situation where the number of items may be higher after initial load (this is corrected after loading more posts). This PR accounts for this and will prevent more posts from being loaded if the number of items exceeds the total number of posts.
=> Post Carousel: Prevent loading more items if complete

base/inc/fields/css/multiple-media-field.less, base/inc/fields/js/multiple-media-field.js, base/inc/fields/multiple-media.class.php
Resolve https://github.com/siteorigin/so-widgets-bundle/issues/877
Screenshot:
=> Add Multiple Media Form Field

admin/admin.js
This PR prevents widget boxes from being larger than they need to be by sizing boxes on a row by row basis.
=> Size Widget box on a row by row basis

widgets/social-media-buttons/data/networks.php
Resolve #1245 
I opted for the base Network URL to be https://www.imdb.com/ as the urls for movies are different to people and there are valid use cases for both.
=> Social Media Buttons: Add IMDb

base/inc/widgets/base-slider.class.php, js/slider/jquery.slider.js
Resolve https://github.com/siteorigin/so-widgets-bundle/issues/906
I went with a separate setting as implementing migration code would require modifying each individual widget (less than ideal as the central slider class was introduced to avoid that need). It would be a good idea to remove the slider dependency on [wp_is_mobile()](https://developer.wordpress.org/reference/functions/wp_is_mobile/) as that isn't cache-friendly, and it's redundant due to the slider breakpoint.
=> Sliders: Add Always show navigation on desktop setting

base/inc/fields/siteorigin-widget-field-class-loader.class.php
Resolve #711
This PR adds two filters to allow for developers to replace all registered prefixes and paths. The filters are:
- `siteorigin_widgets_field_registered_class_prefixes`
- `siteorigin_widgets_field_registered_class_paths`
Here's an example plugin that will replace the TinyMCE with a simple message (it's an example of a major change a developer could make).
[so-override-field.zip](https://drive.google.com/uc?id=18ia1AhnTP70rKsk56i3J592Pkb5Lc1ra)
Screenshot of example plugin:
=> Allow form field class prefix and path filering

widgets/layout-slider/js/slide-control.js, widgets/layout-slider/js/slider-control.js, widgets/layout-slider/layout-slider.php
Resolve https://github.com/siteorigin/so-widgets-bundle/issues/267
This PR introduces a shortcode for the Layout Slider called slider_control. The options for this shortcode are:
- Label - Optional label to use in navigation text.
- Slide - What slide to navigate to.
Slide options are:
- first
- last
- prev
- previous
- next
- slide number (eg. 3)
Unlike the code snippets we previously provided, the slide number isn't zero-based. This means if you wanted to link to the third slide, use 3 rather than 2.
`[slide_control slide="3"]`
[Test layout with slides with various shortcodes setup for testing.](https://drive.google.com/uc?id=1DLDQ3pB6j4S3rLK3jifvG83l7l4L_TXu)
=> Layout Slider: Slider Control Shortcode

base/inc/routes/siteorigin-widgets-resource.class.php, compat/block-editor/widget-block.php
Resolve https://github.com/siteorigin/so-widgets-bundle/issues/850
To test:
- Deactivate Headline widget
- Attempt to use it in a SiteOrgin WIdgets Block, and widget will be activated.
- Add some placeholder data and then save.
- Deactivate Headline widget.
- Reload Block Editor with recently added SiteOrigin Widgets Block with Headline widget.
- Widget will be activated and should preview as expected and the form should be accessiable.
=> Widgets Block: Activate Widgets Automatically

base/inc/routes/siteorigin-widgets-resource.class.php, compat/block-editor/widget-block.js, compat/block-editor/widget-block.php
[Reported here](https://wordpress.org/support/topic/symbol-on-buttons-not-visible/)
This PR resolves an issue where users who use the Widgets Block not displaying icons correctly.
This issue was caused by https://github.com/siteorigin/so-widgets-bundle/pull/1234. Unlike fonts, icons are loaded in the template itself so they won't be enqueued by [the standard widget style enqueue](https://github.com/siteorigin/so-widgets-bundle/blob/1.18.1/compat/block-editor/widget-block.php#L133). That's not something we can change at this point as it's very likely other developers are doing it in the same manner as us, so instead this PR ensures icons are enqueued by storing the icons in an attribute and outputting them when rendering.
Only those who made a change to the SiteOrigin Widgets Block on …
=> Widgets Block: Ensure Icons are enqueued

widgets/slider/slider.php
This PR changes the height defaults to prevent a situation where the foreground is unintentionally given a height. `custom_height` checks for a value so if "default" is used, it'll pass and a height is set. Strangely, I haven't been able to replicate this locally so I'm unsure why default would ever actually be used/accepted.
=> Slider: Remove invalid default

widgets/image-grid/styles/default.less
This will prevent any potential alignment differences after updating to 1.18.x.
Before PR:
After PR (and how it previously looked):
(from https://layouts.siteorigin.com/layout/mono/)
- Import the Mono prebuilt layout, save, and then view the page.
- Switch to PR and make any change to the page (this won't be required for those updating the plugin as the widget CSS will automaetically be cleared). View the page and you'll see the expected alignment. Save, and view the page.
=> Image Grid: Align items using baseline

compat/block-editor/widget-block.js
This doesn't work as expected and isn't required. To test it, save the SiteOrgin Widgets block. If it saves as expected, the change works.
=> Remove redundant Block Saving code.

js/lib/jquery.fitvids.js, widgets/video/js/so-video-widget.js, widgets/video/tpl/default.php, widgets/video/video.php
Resolve https://github.com/siteorigin/so-widgets-bundle/issues/426
This PR adds a setting to the Video Playback that allows users to enable FitVids for the current video player widget. This is handled on a widget by widget basis so if FitVids is disabled for a specific widget, it won't be affected by FitVids (in other words, it's not a global "all or nothing" setting).
Please note that to test this you'll need to use a theme that doesn't load FitVids.js and disable any plugins that enable it. I recommend testing using a Default WordPress theme.
=> Video Player: Add FitVids Support

admin/admin.less
=> Widgets Page: Prevent Menu Search Overlap on Mobile

base/inc/fields/css/icon-field.less
Resolve https://github.com/siteorigin/so-widgets-bundle/issues/1268
Vertical Align adjustment is to prevent a slight offset of the selectors. A build is required for this PR to be tested.
=> Icon: Ensure Filter options are the same height

base/inc/fields/css/media-field.less
Resolve https://github.com/siteorigin/so-widgets-bundle/issues/1288
To test "Media: Increase line-height of Remove to allow for better collapse ", resize the browser to replicate #1288.
To test "Block Editor: Prevent Media Wrapper Overlay on Column Block Resize":
- Create/Open Block Editor powered page.
- Add a Columns block.
- Add a SiteOrigin Widget to one of the blocks, select a widget that uses the Media field (such as the Image widget).
- Resize the column (hover block icon and select the column, go over to the block settings sidebar on the right) to 25 and then clear the width.
=> Media field CSS Changes

base/base.php
This will make it easier for developers to set a valid font weight and font style without having to extract the information manually. Please test this PR using #1275. If that PR works as expected while PR is active, this PR is working as expected.
`weights_raw` is used instead of just `weight` for backwards compatibility. We can't be sure another developer isn't relying on that field to do something similar already so to prevent stepping on toes, we're storing the values separately. 
Here's an example of an array returned by `siteorigin_widget_get_font` can now look like:
```
array(
'family' => 'Alegreya',
'weight' => '600italic',
'weight_raw' => '600',
'style' => 'italic',
)
```
=> Get Font Helper: Extract Weight and Style

widgets/button/button.php, widgets/button/styles/atom.less, widgets/button/styles/flat.less, widgets/button/styles/wire.less
This PR adds a Mobile Align setting to the SO Button Widget. This allows users to change the alignment of the button on mobile to better suit their design. This PR also includes a Responsive Global Addon setting to allow the user to control when the mobile align setting kicks in.
=> Button: Mobile Align Setting

widgets/headline/headline.php, widgets/headline/styles/default.less
This PR prevents an invalid font-weight from being set. It'll ensure `font-style: italic;` is set when an italic font is selected and it'll correctly set a number `font-weight`. Both of these are important if the user is using multiple different variants of the same font because if they're not set in a valid way the wrong variant could show.
=> Headline: Prevent invalid font property

base/inc/widgets/base-slider.class.php, js/slider/jquery.slider.js
Resolve https://github.com/siteorigin/so-widgets-bundle/issues/1253
This PR will ensure that swipe JS will load if a cache is active. To test this PR, please check that `.sow-slider-base` has `.sow-slider-is-mobile` set sub `780px`, and that the swipe JS loads as expected on mobile.
For reference, you can adjust the breakpoint by adjusting the global settings of the widget you're testing.
=> Sliders: Remove Dependency on `wp_is_mobile`

widgets/image-grid/image-grid.php
Related https://developer.wordpress.org/reference/functions/wp_lazy_loading_enabled/
This PR will ensure that external images added using the Image Grid widget have the loaded attribute.
=> Image Grid: Add Loading Attr for External Images

widgets/image/image.php
Resolve https://github.com/siteorigin/so-widgets-bundle/issues/1292
Related: https://developer.wordpress.org/reference/functions/wp_lazy_loading_enabled/
=> Image Widget: Add Support for Loading Attr

base/inc/widgets/base-slider.class.php
This PR adds a Slider Controls setting that allows the user to prevent the looping of background videos. The setting name is based on the setting just above this setting ('Show slide background videos on mobile').
=> Slider: Add "Loop slide background videos" setting

base/siteorigin-widget.class.php, compat/compat.php, so-widgets-bundle.php
Resolve https://github.com/siteorigin/so-widgets-bundle/issues/866
To test this please add the following PHP to [this line](https://github.com/siteorigin/so-widgets-bundle/pull/1258/files#diff-2dc7c68c2b6e69aef4ae1d74975cb590295990126bcd9a32c7f9614f0e0a6f0fR336).
`$force_delete = true;`
Then view WP Admin. View a page that has had its widget CSS cleared and new widget CSS should be generated (as well as the cache regenerated but that's harder to check). If those plugins aren't alerted (and minify isn't managed through their plugins directly) you'll end up with a bunch of 404 notices. If it's working as expected, the page display as expected, and new CSS files will be in the `wp-content/uploads/siteorigin-widgets` directory. Please note that you may need to clear your browser cache for the …
=> Improve cache plugin support

widgets/slider/slider.php, widgets/slider/styles/default.less
This PR changes how the foreground images are sized. Previously, the image height was being used and now it's the custom height. The image size is now used as the `max-height` to prevent distortion if the user picks a height that's larger than the image.
=> Slider: Size Foreground Images using Custom Height 

base/inc/fields/js/multiple-media-field.js
This PR resolves an issue with the Remove button not working as expected after selecting media. Unsure why it previously worked without issue.
To test, add some media and then try and remove it by clicking the Remove button - this field will work for existing media. For an easy method of testing, I recommend using the plugin linked in [this comment](https://github.com/siteorigin/so-widgets-bundle/pull/1235#issuecomment-774980242).
=> Mutiple Media: Correct remove button detection

widgets/contact/tpl/default.php
This PR will resolve a nonce error when submitting a contact form added using the SiteOrigin Widgets Block. To test this PR, add a SiteOrigin Widgets Block with a contact form and fill it out.
These PR are recommended while testing this:
https://github.com/siteorigin/so-widgets-bundle/pull/1306 (so the success message will show)
https://github.com/siteorigin/so-widgets-bundle/pull/1305 (so it's easier to update existing SiteOrgin Widget Blocks)
=> Contact: Don't Set Current URL in Action

compat/block-editor/widget-block.js
This PR brings the SiteOrigin Widgets Block in line with the SiteOrigin Layout Block. Previously, the data of the block would be saved in an inconsistent (to the user) manner, now it will happen after every change (ie. `.change()`). This will allow for more reliable `widgetHtml` generation.
This PR also implements the same update presentation method used by the SIteOrgin Layouts Block to prevent saving before `widgetHtml` is still being generated.
To test this PR, add a block and make some changes. Save the page and then open the page in a different tab. Make a change, save, and refresh the page in the other tab. Has the page updated correctly? Prior to this PR there's a chance that wouldn't be the case.
=> Improve widget block saving

compat/block-editor/widget-block.php
If `$_POST` isn't empty, it's possible widgets could change so to avoid potential situations where the widget has changed (such as with the SO Contact Form on form submission), this PR generate the widget rather than serving `widgetHtml`.
To this PR, please add https://github.com/siteorigin/so-widgets-bundle/pull/1307 and then set up a SiteOrigin Widgets Block with a contact form. Save, and fill out the form. If you see the success message (or error messages) the PR worked as expected.
=> Widget Block: If $_POST isn't empty, render widget

base/inc/fields/icon.class.php
Resolve https://github.com/siteorigin/so-widgets-bundle/issues/1309
This PR will clear the default icon if the icon font family doesn't exist, or if the style doesn't exist. If the style exists, the style will be stripped from the icon name so checking if the font icon allows you to confirm if the style is also set.
To test this open `widgets/icon/icon.php` and replace:
```
'icon' => array(
'type'  => 'icon',
'label' => __( 'Icon', 'so-widgets-bundle' ),
),
```
with:
```
'icon' => array(
'type'  => 'icon',
'label' => __( 'Icon', 'so-widgets-bundle' ),
'default' => 'fontawesome-sow-far-address-card',
),
```
Add an icon widget to any page and confirm the default is set. Now add the following code snippet:
```
add_filter( 'siteorigin_widgets_icon_families', function( $families ) {
unset( …
```
=> Icon Form Field: Clear default if invalid

widgets/image-grid/image-grid.php, widgets/image-grid/styles/default.less
- Renamed Spacing to ~Image Spacing~ Image Padding.
- Removed setting description.
- Added migration code from legacy `measurement` and `number` based spacing to multi-measurement.
- Removed container top padding.
Before loading this PR, please set up a basic Image Grid with a few images to confirm the Spacing to Image spacing migration code works as expected.
=> Image Grid: Spacing Setting Rework

widgets/contact/fields/checkboxes.class.php, widgets/contact/styles/default.less
This PR will allow users to add HTML to checkboxes options. A use case for this is for GDPR type validations ("here's a link to our privacy policy").
=> Contact: Allow whitelisted HTML in Checkboxes options

compat/block-editor/widget-block.php
Notice: Only variables should be passed by reference in C:\xampp\htdocs\church\wp-content\plugins\so-widgets-bundle\compat\block-editor\widget-block.php on line 48
=> Widgets Block: Prevent Notice

widgets/image-grid/image-grid.php
This will prevent the top padding from not having an empty unit of measurement.
=> Image Grid: Prevent Empty Image Padding After Migration

base/base.php
This PR will add a space after the Weight and Variant (300 italic). Previously there would be one (eg. (300italic).
=> Fonts Array: Add A Space Between Weight and Variant

base/inc/fields/js/multi-measurement-field.js
Will default to px. Prevents the following from happening:
=> Multi Measurement: Prevent Empty Unit

admin/admin.js
This PR prevents situations where a single widget can appear on a separate row on larger resolutions. It also fixes an issue that results in columns being sized by invisible widgets.
=> Widgets Page Mismatched Column Fixes

base/inc/widgets/base-slider.class.php
This PR will resolve the following error when something uses the `siteorigin_widgets_slider_overlay_attributes` and unsets either the `class` or `style` item.
`[07-Jun-2021 13:01:41 UTC] PHP Fatal error:  Uncaught TypeError: implode(): Argument #1 ($pieces) must be of type array, string given in /Users/amisplon/Sites/siteorigin/wp-content/plugins/so-widgets-bundle/base/inc/widgets/base-slider.class.php:361`
=> Slider: Avoid Potential PHP 8 Error with Overlay Attr Filter

base/inc/fields/posts.class.php, base/inc/post-selector.php
This PR will add a new setting to the posts form field that will allow users to change the taxonomy relationship. Previously, it was only possible to adjust the taxonomies relationship by using the `siteorigin_widgets_posts_selector_query` hook.
=> Post Selector: Add option to adjust taxonomies relationship

base/base.php
This PR will ensure there's no spacing present there's a variant present, but no font weight (eg. " italic").
=> Font Variant: Correct Spacing When No Weight

base/inc/widgets/base-slider.class.php
Unsure how the semi-colon was replaced with a space.
=> Slider: Resolve Overlay Style Bug

base/js/admin.js
This PR adds support for labels to show the item index in the label. It dos this by adding a new option for item_labels called increment. This change supports two possible position: `before` and `after`.
To this this PR, open` wp-content/plugins/so-widgets-bundle/widgets/features/features.php` and find:
```
'item_label' => array(
'selector'     => "[id*='features-title']",
'update_event' => 'change',
'value_method' => 'val',
),
```
Replace that with:
```
'item_label' => array(
'selector'     => "[id*='features-title']",
'update_event' => 'change',
'value_method' => 'val',
'increment' => 'before',
),
```
(change increment to after to test the option option)
=> Repeater: Add Item Increments Labels

base/inc/fields/css/multiple-media-field.less, base/inc/fields/multiple-media.class.php
This PR allows for non-Image to be seen in the widget after saving the page (previously you could add them, but couldn't select/view them when editing the widget after loading), and adds the `image_dimensions` parameter to allow for developers to set specific dimensions.
[Test widget](https://drive.google.com/uc?id=14vytZ86-OK8xNPvzE6MRUD8I9JlXrwlp)
This PR also reduces the thumbnail dimensions from 75x75 to 64x64. This is to reduce stretching with WP Media Type Icons.
=> Multiple media: Improved Image Support & `image_dimensions` parameter 

base/base.php
This PR ensures every selected instance of a Google Font is imported. It'll avoid a situation where one widget imports a font at a specific weight, and another widget attempts to import the same font with a different weight but it fails as the font has already been imported once.
[Here's a test layout](https://drive.google.com/uc?id=11tWzPWgxQQ5YT9GMnWnkDDTTwWI_tqiV) to test this PR. Once imported, view the page source and search for the Google Font import (search for `fonts.googleapis.com`) and open the URL in a different tab. Ensure all of the selected fonts sizes and styles are imported. For reference, that layout should have the following fonts weights and styles imported:
- 600 italic
- 300
- 400
- 600
=> Google Font Import: Ensure all weights and styles are imported

js/sow.google-map.js
[Reported here](https://wordpress.org/support/topic/google-maps-widget-is-scrolled-into-view-on-page-load/).
This PR will prevent the browser from being auto scrolled down to the Google Map on load when a marker is set and **When should Info Windows be displayed?**  is set to **Always**.
[Test Layout](https://drive.google.com/uc?id=1tKmYeMv7g5QTyeIvrw0p8eZLaTMvVwbP) (confirm the scroll doesn't occur when the PR is present)
=> Google Maps: Avoid Jump on Load When InfoDisplay Always Enabled

widgets/button/button.php, widgets/button/styles/atom.less, widgets/button/styles/flat.less, widgets/button/styles/wire.less, widgets/contact/contact.php, widgets/contact/styles/default.less, widgets/features/features.php, widgets/features/styles/default.less, widgets/hero/hero.php, widgets/hero/styles/default.less
This PR implements https://github.com/siteorigin/so-widgets-bundle/pull/1278 for the following widgets:
- Button
- Contact
- Features
- Hero
This PR ensures the correct font is loaded by setting the correct font weight and style as needed. Prior to this PR, it was possible the font wouldn't be loaded correctly and/or be overridden by other instances of the font being loaded. I've created a basic test layout that tests all of the adjusted font fields and it can be downloaded by [clicking here](https://drive.google.com/uc?id=1jkfnAmCAc3BBmV3NAt4PWaCZ12sbbAcm). Please test this PR by confirming the font [the font-weight and font-style is correctly set for the text](https://i.imgur.com/DMZOPif.png).
For reference, here's the Headline version of this PR: …
=> Update Various Widgets To Use Font Helper Updated Options

base/inc/fields/css/multiple-media-field.less, base/inc/fields/js/multiple-media-field.js, base/inc/fields/multiple-media.class.php
This PR adds an optional title field for the Multiple Media form field.
To test this PR install [this plugin](https://drive.google.com/uc?id=14vytZ86-OK8xNPvzE6MRUD8I9JlXrwlp) and enable the SiteOrigin Multiple Media Test widget. Add it to the page and add a few items, and you'll see the title below the image.
Now to test disabling the title open wp-content/plugins/siteorigin-multiple-media-widget-pr-1329/widgets/multiple-media/multiple-media.php and find:
`'label' => __( 'Multiple Media', 'sowb-multiple-media' ),`
Add to the next line:
`'title' => false,`
=> Multiple Media: Optional Title

base/siteorigin-widget.class.php
This PR will fix the SITEORIGIN_WIDGETS_DEBUG constant to allow for the widget CSS cache to be completely bypassed by inlining all widget CSS inline instead. This can be tested by adding the following PHP to wp-config.php:
`define( 'SITEORIGIN_WIDGETS_DEBUG', true );`
Docs: https://github.com/siteorigin/docs/pull/118
=> Ensure SITEORIGIN_WIDGETS_DEBUG Bypasses Widget CSS Cache

widgets/headline/headline.php, widgets/headline/styles/default.less
Resolve https://github.com/siteorigin/so-widgets-bundle/issues/1343
This PR adds mobile alignment settings for the headline, sub-headline, and divider. It also adds a global widget breakpoint setting that allows users to control the mobile alignment CSS is used.
Pre-existing widgets will have Mobile alignment set to the same value as the related Alignment setting. Please test to ensure the migration works as expected by setting up a few headlines prior to switching to the PR branch.
=> Headline: Mobile Alignment Settings

base/inc/post-selector.php
This PR will resolve below warnign when you manually input another term rather than using the Post Selector. 
`Resolve Warning: Undefined array key 1 in wp-content/plugins/so-widgets-bundle/base/inc/post-selector.php on line 39`
This error occurs as no taxonomy is set. This PR will use the last taxonomy if it's valid, or default to category.
To test this open a post loop widget and select two taxonomies. Remove the second term and colon (eg. category:). So your taxonomy field should go from:
`category:test,category:test2`
To:
`category:test,test2`
=> Post Selector: If No Taxonomy Set, Default to Previous Taxonomy or Category

widgets/hero/hero.php, widgets/layout-slider/layout-slider.php, widgets/slider/slider.php
This PR updates all slider widgets to ensure item labels are set wherever possible for repeaters rather than the generic Frame/Title. 
Item label priority order:
Slider frame:
- Background Image
- Background Video
- Background Video URL
- Background Foreground
Hero and Layout Slider:
- Background Image
- Background Video
- Background Video URL
All Video Backgrounds
- Local Video
- External video URL
=> Slider Widgets: Update Automatic Item Labels

widgets/slider/slider.php
This PR prevents a display issue when using [Jetpack Site Accelerator](https://jetpack.com/support/site-accelerator/) by preventing the slider image from being lazy loaded. I tested a few other Lazy Load plugins and they don't cause this same issue.
=> Slider: Disallow Jetpack Lazy Load

base/inc/fields/js/presets-field.js, base/inc/fields/presets.class.php, base/siteorigin-widget.class.php
This commit includes three preset specific changes:
**Preset Field: Store Selected Preset**
This commit allows for the selected preset to be saved.
**Preset: Add `default_preset` to allow default Preset** 
This commit allows the preset field to support a default preset. This change was complicated due to how state emitters work.
The `default_preset ` parameter was used over `default` due to how `default` being a valid form field option and it not allowing for reliable default detection in the preset JS.
**SiteOrigin Widget: dynamic_preset_state_handler** 
This commit allows a method of dynamically setting the state_handler of an array of `form_fields` based on the values used by the preset field. This basically means, we can easily show/hide fields based on the preset values. This is …
=> Preset Form Field Adjustments

base/inc/fields/builder.class.php, base/siteorigin-widget.class.php
Resolve https://github.com/siteorigin/so-widgets-bundle/issues/1361
Layout Builder: https://github.com/siteorigin/siteorigin-panels/pull/905
This change was done to prevent Builder widgets in widget areas from generating a CSS file for every page. It will exclude non-widget area fields, but there's no way around that.
Pre-existing widgets with builder fields (eg. Accordion widget) will need to be saved to be excluded.
=> CSS Cache: Don't add page id to widgets in builders

base/inc/widgets/tpl/carousel.php
Escaping this here will only result in the HTML being output. The output itself doesn't need to be escaped as it's predefined elsewhere.
=> Anything Carousel: Don't escape before/after_title

js/lib/slick.js
This PR implements https://github.com/siteorigin/slick/pull/1/commits/db32990c3cec28cf701d148be874e60dcd55e0e3 to resolve an issue with the carousel widgets not being responsive.
=> Carousel Responsive Fix

base/css/admin.less
This PR fixes the alignment of the "select content" button in the Links field.
=> 5.8 Widgets: Fix Alignment of Links Button

base/css/admin.less
This PR corrects the font of the widget preview button in the 5.8 Widget Area.
=> 5.8 Widgets: Widget Preview Button Text

base/inc/fields/css/measurement-field.less
This PR increases the spacing after the measurement field input. It's now in line with the multi-measurement field spacing.
=> Measurement: Increase Spacing After Input

base/inc/fields/css/image-size-field.less, base/inc/fields/image-size.class.php, base/js/admin.js
This PR fixes the selector was previously specific to a field called "size" rather than all image size fields. This resulted in the field being unstyled. Test this using https://github.com/siteorigin/so-widgets-bundle/pull/1371
This PR also adds spacing between the dimensions:
This PR also excludes the custom image sizes dimension fields from state emitters to prevent a situation where they'll unintentionally result in state changes. You can test this using https://github.com/siteorigin/so-widgets-bundle/pull/1371.
=> Image Size Adjustments

base/css/admin.less
This is a follow up to https://github.com/siteorigin/so-widgets-bundle/pull/1088. That PR attempted to get around the potential situation where fields would be larger than 600px but it doesn't work if something makes the widget area smaller - this is what happens when you open the search field in the 5.8 widget area but it's not specific to that interface.
I found no negative results by completely removing the min-width. It's possible there could be some so please test any situation you can think of.
=> Remove WB form min-width

widgets/anything-carousel/css/style.less, widgets/anything-carousel/styles/base.less
This PR includes a number of changes to the Anything Carousel Widget.
**Set Wrapper Full Width To Avoid Sizing Issue**
This PR resolves an issue where having fewer items than your slides to scroll setting will result in the carousel items that are present not being sized correctly. To test this, add a single carousel item with placeholder content and then preview the widget.
**Prevent Link Color From Overriding Nav Arrows**
The PB Link Color setting is overriding the Nav Arrow color. This PR prevents that by using by forcing the colors using `!important`. 
**![2021-07-27_04-56-30-1542](https://user-images.githubusercontent.com/17275120/127044705-ca49e89e-471e-408e-bd92-6a13aedf8b03.jpg)**
**Prevent Active Dot Pointer Cursor** 
This PR resets the cursor when hovering over the active …
=> Anything Carousel Adjustments

compat/beaver-builder/styles.less
This PR resolves a display issue with the color picker in Beaver Builder:
=> Beaver Builder: Fix Color Picker Styling

compat/block-editor/widget-block.php
To test this PR please open the 5.8 widget area while WP_DEBUG_LOG is enabled.
`( ! ) Notice: wp_enqueue_script() was called <strong>incorrectly</strong>. "wp-editor" script should not be enqueued together with the new widgets editor (wp-edit-widgets or wp-customize-widgets). Please see <a href="https://wordpress.org/support/article/debugging-in-wordpress/">Debugging in WordPress</a> for more information. (This message was added in version 5.8.0.) in C:\Users\Alex\Documents\local-sites\wp-nightly\app\public\wp-includes\functions.php on line 5535`
=> SO Widgets Block: 5.8 Widgets Area Notice Fix

base/css/admin.less
This PR will correct the Preview Button line-height.
=> New Widget Area: Preview line-height fix

base/inc/widgets/base-carousel.class.php, widgets/anything-carousel/anything-carousel.php, widgets/post-carousel/css/style.less, widgets/post-carousel/post-carousel.php, widgets/post-carousel/styles/default.less, widgets/post-carousel/tpl/item.php
This PR adds a new method for carousels called `design_settings_form_fields`. This will allow for more centrally structured design settings. This PR then modifies both carousel widgets to use this new method. For the post carousel specifically, it:
- Migrate settings to correct design sub-sections.
- Adds support new title settings.
Please test that pre-existing Post Carousel and Anything Carousel widgets work as expected (specifically, the post carousel design settings migrate over correctly) after switching to this PR.
=> Carousel: Add design_settings_form_fields & Post Carousel Design Field Adjustments

widgets/social-media-buttons/data/networks.php
Google+ has been completely shut down.
=> Social Media Buttons: Remove Google+

js/sow.google-map.js
This PR changes how Google Maps are set up to allow to avoid situations where a Google Map won't display correctly if invisible on load, or if the parent is invisible. It'll also allow developers to manually reinitialize the map if they wish to by using `sowb.setupGoogleMaps( false, true );` This PR will also more aggressively prevent itself from loading multiple instances of the Google Maps API script.
Please test:
- SiteOrigin Google Maps widget
- SiteOrigin Contact Form Location Field
- Google Maps inside of Accordion/tab widget
- Please test with a combination of only, and all as there could be a situation where the map will only display as expected if other maps are also present.
=> Google Maps: Change How Maps Are Setup To Allow Greater Flexibility

widgets/video/video.php
Previously, External Videos set to not Use oEmbed wouldn't play. This PR fixes that by passing the source as a valid `video source`.
=> Video Player External Video: Resolve MeidaElements issue

widgets/button/button.php
[Reported here](https://siteorigin.com/thread/so-widgets-bundle-generating-an-error/)
Resolves the following error:
> Fatal error: Uncaught TypeError: Cannot access offset of type string on string in /home/qwerty/public_html/wp-content/plugins/so-widgets-bundle/widgets/button/button.php:433
This isn't simple to test as the error requires a very specific setup so just confirm the Button widget displays as expected.
=> Button: Ensure $instance isn't empty before modifying it

js/carousel.js
This PR resolves an issue where the Anything Carousel Navigation Dots indicator will be cleared when attempting to navigate past the last slide. The Post Carousel has a loading indicator so we need to pad the `lastPosition`.
Please test this PR using both carousels. With and without looping.
=> Carousel: Only Increase LastPos for Post Carousel

base/inc/video.php
This PR will ensure that videos added using `get_video_oembed` (ie. SiteOrigin Slider Background Video) are automatically muted when autoplay is enabled. This is required for the video to autoplay in Chrome.
=> get_video_oembed: Mute YouTube videos set to autoplay

base/inc/widgets/base-slider.class.php, widgets/hero/hero.php, widgets/layout-slider/layout-slider.php, widgets/slider/slider.php
This moves the `Loop slide background videos` in the Slider Controls setting group to frames - after the Background Videos repeater in the Slider widget, and at the very end of the Background section for the rest of the Slider widgets. If the user previously had this setting enabled, the frame by frame setting will be automatically enabled.
- Add two of each slider to the page and set up 2 or so slides with videos set.
- Tick the Loop slide background videos in one instance of a slider widget and leave the other one unticked.
- Save. Export the layout (just to be safe),
- Switch to this branch.
- Confirm that the frame specific `Loop slide background videos` setting is correctly ticked when it should be, and confirm the videos loop.
- Once confirmed the migration worked …
=> Sliders: Handle Video Loop Setting on a Frame by Frame Basis

widgets/video/tpl/default.php, widgets/video/video.php
Resolve https://github.com/siteorigin/so-widgets-bundle/issues/1368
This PR removes the Video Player Controls setting in favour of a filter.
To test this filter:
- Add a SiteOrigin Video Player widget.
- Add a local self hosted video.
- Use widget preview. Note no controls.
- Add the following code snippet:
`add_filter( 'sow_video_add_controls', '__return_true' );`
- Preview widget again and note controls.
=> Video Player: sow_video_add_controls filter

base/inc/fields/js/presets-field.js
This PR will always remove the default placeholder field if `default-preset` is set.
You can test this PR using https://github.com/siteorigin/so-widgets-bundle/pull/1359
- Add a Blog widget.
- Save and reload.
- Open Blog widget and note that there's an empty option in the Template (presets) option.
- Add the changes in this PR to that branch and refresh the page again.
- Open the Blog widget and note that there's no longer an empty field in the Template (presets) option.
=> Preset: Always Remove Default if default-preset is set

base/inc/widgets/base-carousel.class.php, widgets/anything-carousel/anything-carousel.php, widgets/anything-carousel/styles/base.less, widgets/post-carousel/css/style.less, widgets/post-carousel/post-carousel.php, widgets/post-carousel/styles/default.less
This PR allows you to control on what devices the navigation will appear on. It affects both the Anything Carousel and Post Carousel. By default, the navigation is enabled for everything but the Post Carousel on Mobile - this is due to legacy reasons.
This PR also moves the Breakpoint setting above the Slides to Scroll setting.
=> Carousel Responsive Navigation Setting

js/carousel.js, widgets/anything-carousel/anything-carousel.php
This PR will add an anchor tag to the Anything Carousel widget wrapper, and it also adds a new event for the carousel `carousel_setup` that is triggered after all carousels are set up.
=> Anything Carousel Anchor Setup

base/siteorigin-widget.class.php
This PR allows for multiple teasers (output randomly), and it appends a period to the end of the teaser.
To test this PR, [replace the highlighted here](https://github.com/siteorigin/so-widgets-bundle/blob/1.25.1/widgets/image/image.php#L268-L276) with:
```
return array(
sprintf(
__( 'This is a test for a test addon%s', 'so-widgets-bundle' ),
'<a href="https://siteorigin.com/downloads/premium/?featured_addon=plugin/test" target="_blank" rel="noopener noreferrer">',
'</a>'
),
sprintf(
__( 'Add a Lightbox to your images with %sSiteOrigin Premium%s', 'so-widgets-bundle' ),
'<a href="https://siteorigin.com/downloads/premium/?featured_addon=plugin/lightbox" target="_blank" rel="noopener noreferrer">',
'</a>'
),
);
```
=> Teaser Adjustments

base/siteorigin-widget.class.php, widgets/hero/hero.php
This PR allows for a button to the Hero widget to have a $. To test his PR set up a frame and add a button. Set the text to: `$25` and then save. How does that look?
(it's possible for certain other combinations to work, but using a price is the simplest way to removed it).
=> Hero: Allow Buttons to Contain $

js/sow.google-map.js, widgets/google-map/fields/js/location-field.js
This PR resolves a few JS related errors and notices that can result in SiteOrigin Google Maps widget not working as expected or other widgets/blocks being negatively affected.
- Please confirm no console errors occur when previewing the map (outside of generic WordPress errors).
- You're able to use the Location field after viewing the Block Preview first.
- You're able to preview the map after using the Location field first.
=> Block Editor: Resolve Google Map Widget Errors

widgets/social-media-buttons/data/networks.php, widgets/social-media-buttons/social-media-buttons.php
This PR is a follow up to https://github.com/siteorigin/so-widgets-bundle/pull/1399. That PR assumes all users were solely using that network for _just_ Google Plus, but there are reasons why a user may have used that icon without it being directly connected to Google Plus - such as Google Business reviews.
This PR adds a Google network option and adds migration code for any instances that were previously using the Google Plus network.
=> Social Media Buttons: Add Google Network

base/inc/fields/css/multiple-media-field.less
- The Add Media button requires `box-sizing: border-box;` to ensure the sizing is correct.
- `box-sizing: content-box;` only needs to be applied to the items.
Before:
After:
=> Multiple Media: box-sizing Adjustments

base/inc/widgets/base-carousel.class.php, js/carousel.js, widgets/anything-carousel/anything-carousel.php, widgets/post-carousel/post-carousel.php
Resolve https://github.com/siteorigin/so-widgets-bundle/issues/1414
This commit introduces a dedicated Slides to Show setting. Previously, the number of slides to scroll and the number of slides to show was directly linked so the Slides to Scroll setting was simply renamed for the Anything Carousel widget.
While testing, please confirm that the responsive settings for the Anything Carousel widget carry over as expected - any slides to scroll adjustments should be replicated in the Slides to Scroll setting.
=> Carousel: Slides to Show Setting

widgets/button/tpl/default.php
This will allow for users to add JS using apostrophes without it being slashed in a manner that makes it unusable. I've run some additional tests with how certain JS is handled by this change and I don't notice any direct issues by making this change.
Test JS:
`console.log('This will not output anything to the console prior to this PR');`
=> Button: Allow for apostrophe in onclick

compat/compat.php
This PR adds auto clearing cache support for:
- [Hummingbird](https://wordpress.org/plugins/hummingbird-performance/)
- [Breeze](https://wordpress.org/plugins/breeze/)
For testing instructions, please refer to [the initial PR](https://github.com/siteorigin/so-widgets-bundle/pull/1258) for this functionality,
This PR also prevents a situation where the file extension is included in the `$id` detection which will prevent the  CSS Cache from clearing correctly.
=> CSS Cache Compat: Hummingbird, Breeze, and potential `$Id` detection issue

base/inc/widgets/base-slider.class.php
This PR resolves the following error:
`[05-Dec-2021 09:57:03 UTC] PHP Notice:  Undefined index: height_responsive_unit in /***/public_html/wp-content/plugins/so-widgets-bundle/base/inc/widgets/base-slider.class.php on line 351`
=> Slider Setting Migration: Check If Subsection Value Exists Before Migration

js/sow.google-map.js, widgets/google-map/fields/js/location-field.js
This PR resolves an issue that results in the SiteOrigin Widget Block not working if the Google Map widget is set up. It also switches to an event-based init to allow for the location field and map override each other - this could also help with third-party plugins.
`sow.google-map.js?ver=dev:567 TypeError: Cannot read properties of undefined (reading 'Geocoder')`
To test this PR,
- Check that you're able to set up a Google Map on a Classic Editor powered page.
- Set up a SiteOrigin Widget Block with a Google Map able to display.
- Set up a SiteOrigin Layouts Block with a SiteOrigin Google Maps widget setup and previewing (ideally at the same time as the SiteOrigin Widgets Block version).
=> Google Map: Improved Init, global Google Maps Var usage, and SO Widgets Block Dispaly Issue Fix

widgets/features/features.php
This PR alters the Features widget repeater to use the Feature title and Feature Icon title fields for the repeater item label.  If both are set, the title will take priority.
=> Features: Set Feature Item Label to Title or Icon

widgets/accordion/js/accordion.js, widgets/accordion/tpl/default.php
This PR will change how the Accordion hides closed panels so that they're automatically hidden before page load to load.
=> Accordion: Hide Closed Panels Prior to Load

base/inc/widgets/base-carousel.class.php, js/carousel.js
This PR adds an Animation setting to the Anything Carousel widget. This allows you to set the Anything Carousel up to continuously scroll rather.
- Please add a Siterigin Anything Carousel and add enough items to allow for a number of scrolls.
- Open the settings and set `Animation` to `Linear`.
- Set Timeout to 1 for the best overall results.
- Consider reducing the `Slides to Scroll` setting to `1` and setting the Animation to a lower amount to speed up the scroll - try `2500`.
=> Anything Carousel: Animation Setting

widgets/accordion/styles/default.less, widgets/tabs/styles/default.less
`border-radius` doesn't need an actual width so this PR removes the dependency on `border-width`.
=> Accordion/Tabs: Remove `border-radius` dependency on `border-width`

compat/compat.php, widgets/slider/slider.php
This PR resolves an AMP compatibility issue with the `loading` attribute `eager` value. If the [AMP plugin](https://wordpress.org/plugins/amp/) is active and enabled, this PR will prevent the Slider widgets `loading` attribute override for images. 
`siteorigin_widgets_slider_attr` filter to do this. This was done in response to [this thread](https://wordpress.org/support/topic/disallowed-attribute-value/) and you can test this issue by checking the attribute of the SiteOrigin Slider Foreground and Background Image to ensure it's set to loading and `skip-lazy` isn't a set class for the image.
=> Slider: Disable `loading` override when AMP plugin is active

compat/block-editor/widget-block.php
[Reported here](https://wordpress.org/support/topic/post-carousel-doesnt-update-automaticly/)
This PR will exclude the Post Carousel widget from the SO Widget Blocks html cache. This is done to ensure that the post carousel always shows the latest posts.
=> Widgets Block: Exclude Post Carousel From Caching

compat/block-editor/widget-block.php
This PR will resolve the following Updraft Central error: I'm unsure when this error occurs as the logs don't provide further context but based on the context it's likely outside of WP Admin.
` The remote site has encountered a fatal error while executing the requested command. Remote response follows: PHP Fatal error (Error) has occurred during UpdraftCentral command execution. Error Message: Call to undefined function get_current_screen() (Code: 0, line 27 in /htdocs/wordpress/wp-content/plugins/so-widgets-bundle/compat/block-editor/widget-block.php) `
=> Widgets Block: Prevent Potential Undefined Error Outside of WP Admin

compat/block-editor/widget-block.php
This PR will exclude the Contact Form widget from the SO Widget Blocks HTML cache. This is required due to a nonce check. No other widgets rely on nonces so no other widgets need to be excluded for the same reason.
- You can test this build by adding a SIteOrigin Widgets Block with a contact form set. Save.
- View the page in a different browser and submit the form and it'll be rejected.
- Apply this PR and open a new tab with the page with the contact form.
- Submit it again and it should submit as the first time without issue.
=> Widgets Block: Exclude Contact Form From Caching

widgets/social-media-buttons/social-media-buttons.php, widgets/social-media-buttons/styles/atom.less, widgets/social-media-buttons/styles/flat.less, widgets/social-media-buttons/styles/wire.less
This PR will introduce `Icon color hover` and `Background color hover` settings. These settings are visible after enabling the `Use hover effects`. If these settings aren't set, the previous button styling will be used.
=> Social Media Buttons: Hover Background and Icon Color

widgets/button/button.php, widgets/button/tpl/default.php, widgets/contact/contact.php
This PR will prevent the contact widget, and the Button widget (and any widget that includes it as a sub widget) from being flagged by Wordfence for having a setting called `onclick`.
1. Set up a test page with a button widget and a contact form. Set the onclick in both widgets to anything (doesn't need to be valid JS, just needs to be set).
2. Install Wordfence and open the button widget to confirm the block. Do the same for the contact form.
3. Disable Wordfence.
4. Enable this PR, reload the test page and save it (this is to save the migrated `onclick` settings to the `on_click` structure.
5. Re-enable Wordfence. Check if widgets are blocks.
If you're having trouble causing the base block, it's possible you may have previously set Wordfence to bypass this block. You …
=> Button and Contact: Migrate `onclick` to `on_click` to avoid WF flag

widgets/cta/cta.php
Resolve https://github.com/siteorigin/so-widgets-bundle/issues/1446
It's been long enough where the **Use default background colors** isn't required anymore. The chance of someone upgrading from a version prior to that setting and having cleared the background and border color settings is _very_ low.
=> CTA: Remove `Use default background colors` setting

widgets/social-media-buttons/styles/atom.less
Previously, the icon_cover override didn't override in a reliable manner.
=> Social Media Buttons: Icon Color Hover fix

compat/block-editor/widget-block.php
[Reported here](https://wordpress.org/support/topic/php-notices-on-wp-5-9/)
To test this please ensure no notice occurs when viewing a Block Editor powered page, or when using the new Widget Area.
=> Widgets Block: Fix Logic Typo Resulting in Potential Notice

base/inc/fields/js/presets-field.js, base/siteorigin-widget.class.php
This PR ensures that state emitters are correctly triggered when opening a widget that uses a presets field for state emitter. It also adds a key that contains all of the presets that adjust sections to allow for more automatic section hiding.
Please test this PR using https://github.com/siteorigin/siteorigin-premium/pull/587
Prior to this PR **Design > Category** settings group will appear while using the Default theme. If you save with the Overlay theme selected the Default sections will appear when re-opening the widget.
=> Presets: Trigger Init and Improved Automated Section Hiding

widgets/post-carousel/post-carousel.php
To test this disable the SiteOrigin Premium, confirm the Post Carousel has the dot navigation. Then enable this PR and the dot navigation will disappear when using the Base theme.
=> Post Carousel: Prevent Dot Navigation From Outputting in Base Theme

base/inc/widgets/base-carousel.class.php
This will ensure the Post Carousel widget doesn't have a Navigation Dots setting in the Carousel settings group when the Overlay theme isn't active.
=> Carousel: Remove Navigation Arrows/Dots From Carousel Settings

widgets/post-carousel/post-carousel.php
This PR will resolve the below notice that can occur for Post Carousel widgets that were created prior to the introduction of the Item Tag setting.
`PHP Notice: Undefined index: design in /public_html/wp-content/plugins/so-widgets-bundle/widgets/post-carousel/post-carousel.php on line 348`
=> Post Carousel: Prevent Potential Item Tag Notice

compat/block-editor/widget-block.js, compat/block-editor/widget-block.php
This PR will:
- Fix an issue that prevented ajax errors from showing these were present when trying to use a deactivated third party widget. This error could occur even when the widget was active and that would make the widget unusable.
- Prevent a third party widget data unintentionally having the wrong author.
- List the author in widget names for all third party widgets. This was previously the case for only certain widgets. `Widget Name by Author`.
You can test this PR using the [Livemesh SiteOrgin Widgets](https://wordpress.org/plugins/livemesh-siteorigin-widgets/) plugin.
=> Widget Block Third Party Widget Changes

js/carousel.js
This PR will replace the Slick autoplay with our own method of handling it. This will allow the autoplay to account for the non-standard method of handling navigation in the Post Carousel widget.
Please test this PR with both the Post Carousel and Anything Carousel widgets. Try a few different timeouts and confirm the **Autoplay pause on hover** setting setting works as expected.
You can enable continuous scroll for the Post Carousel widget by enabling looping and autoplay.
=> Carousel: Override Slick Autoplay & Add Continuous scroll to Post Carousel

compat/block-editor/widget-block.php
Resolve `( ! ) Notice: Undefined index: widgetData in app\public\wp-content\plugins\so-widgets-bundle\compat\block-editor\widget-block.php on line 149`
=> Widgets Block: Resolve notice when rendering if widget isn't selected

base/inc/widgets/base-carousel.class.php, js/carousel.js, widgets/post-carousel/post-carousel.php
This PR is a follow up to https://github.com/siteorigin/so-widgets-bundle/pull/1462. It changes how the looping of the post carousel is handled when you reach the end of the post. Instead of transitioning back to the first item it "scrolls" to the first items in a more continuous fashion. Due to how visually different this is compared to the base method, it's behind a setting to prevent an unexpected change.
You can enable continuous scroll for the Post Carousel widget by enabling looping, autoplay, and the **Autoplay Continuous Scroll** setting.
=> Post Carousel: Add Autoplay Continuous Scroll

widgets/anything-carousel/styles/base.less
Resolves the following error:
`( ! ) Less_Exception_Compiler: variable @navigation_arrows is undefined in file anonymous-file-0.less in anonymous-file-0.less in C:\Users\alex\Local Sites\siteorigin\app\public\wp-content\plugins\so-widgets-bundle\base\inc\lib\Less\Tree\Variable.php on line 49`
This error resulted in there not being any spacing between the Anything Carousel items.
[Test layout](https://drive.google.com/uc?id=15Zmh2hE3iFmc3VTIsYeRZFrKJiFV9FAV)
=> Anything Carousel: Resolve `Less_Exception_Compiler` notice

base/inc/widgets/tpl/carousel.php
Related to https://github.com/siteorigin/so-widgets-bundle/pull/1476
This PR will prevent the Post Carousel Overlay Carousel from appearing when the navigation arrows are disabled.
=> Carousel: Hide Container Arrows If Disabled

base/inc/widgets/base-slider.class.php, widgets/hero/styles/default.less, widgets/hero/tpl/default.php, widgets/layout-slider/styles/default.less, widgets/layout-slider/tpl/default.php
This PR inlines the set desktop height for the slider. It then undersets it on load to prevent a situation where the mobile height could be smaller.
=> Layout/Hero: Inline Height To Prevent Potential Jump

widgets/anything-carousel/anything-carousel.php, widgets/post-carousel/post-carousel.php
This will prevent a situation where the navigation arrows will still output even when the navigation arrows are disabled.
=> Carousel: Improve Navigation Arrow Fallback

js/carousel.js
Resolve https://github.com/siteorigin/so-widgets-bundle/issues/1481
[Please test this PR using this PR.](https://drive.google.com/uc?id=1x9B6UCnaVE9ZIT7oEyQhSXJmnQiQPF2N) Prior to this PR the Anything Carousel dot navigations won't work correctly and after enabling this PR they'll work as expected.
=> Carousel Dots: Resolve Miscalculation When Multiple Carousels Are Present

widgets/contact/contact.php, widgets/headline/headline.php, widgets/icon/icon.php, widgets/image-grid/image-grid.php, widgets/simple-masonry/simple-masonry.php, widgets/social-media-buttons/social-media-buttons.php, widgets/taxonomy/taxonomy.php
This PR resolves the issue discussed in https://github.com/siteorigin/so-widgets-bundle/pull/1478. #1478 isn't required if a help link is present.
=> Added missing widget help links

widgets/contact/contact.php
This PR will allow for users to add additional headers to the contact form using the `siteorigin_widgets_contact_email_headers` filter.  For example, the following snippet will CC `test@example.com`.
```
add_filter( 'siteorigin_widgets_contact_email_headers', function( $headers ) {
$headers[] = 'Cc: test@example.com';
return $headers;
} );
```
=> Contact: Add `siteorigin_widgets_contact_email_headers`

widgets/social-media-buttons/styles/atom.less, widgets/social-media-buttons/styles/flat.less, widgets/social-media-buttons/styles/wire.less
- Clean up selectors to prevent CSS output that's never used.
- Flat: Correctly override Icon color hover.
- Remove :visited and :active in favour of :hover and :focus
- Ensure hover styling isn't output when hover styles are disabled.
=> Social Media Buttons: Hover Adjustments

widgets/image-grid/image-grid.php, widgets/image/image.php
This PR alters the Image and Image Grid widget to use [wp_get_loading_attr_default](https://developer.wordpress.org/reference/functions/wp_get_loading_attr_default/). This will prevent a situation where the image can cause a large contentful paint due to being set to lazy load above the fold. For users who would like to fine-tune how many images are excluded from lazy loading they can use the `wp_omit_loading_attr_threshold` filter to control that.
To test this, please add two valid SiteOrigin Image widgets. Check the markup of the first image and confirm no loading, and confirm it's present in the second one. Repeat this process for the Image grid widget. Please note that if a featured image is set, that'll be excluded from the lazy load isntead.
=> Image Widgets: Use `wp_get_loading_attr_default`

base/inc/widgets/base-slider.class.php
[Reported here](https://siteorigin.com/thread/php-errors-siteorigin-widget-bundle/)
This PR resolves the following notices that occur while using PHP 8.
```
Undefined variable $instance (count1)
wp-content/plugins/so-widgets-bundle/base/inc/widgets/base-slider.class.php:400 – Plugin: so-widgets-bundle
Trying to access array offset on value of type null (count3)
wp-content/plugins/so-widgets-bundle/base/inc/widgets/base-slider.class.php:400 – Plugin: so-widgets-bundle
```
=> Resole Slider PHP 8 notices

widgets/image-grid/image-grid.php, widgets/image/image.php
Follow up to https://github.com/siteorigin/so-widgets-bundle/pull/1492.
`wp_get_loading_attr_default` doesn't work in widget areas so if a SiteOrigin Image widget is added to prior to the content it'll always be lazy loaded. It also doesn't work for versions of WordPress 5.9 (which is expected). This PR adds the `siteorigin_widgets_WIDGET_NAME_lazy_load` filter to the Image and Image Grid widgets. This will allow for the developer to programmatically exclude an image using PHP. For example, the following PHP will prevent the image with id 6119 from being lazy loaded:
```
add_filter( 'siteorigin_widgets_image_lazy_load', function( $lazy, $instance, $widget ) {
return $instance['image'] !== 6119 ? $lazy : '';
}, 10, 3 );
```
Filter for image grid is: …
=> Add `siteorigin_widgets_WIDGET_NAME_lazy_load` filter

widgets/lottie-player/lottie-player.php
This text is shown below the widget title in the page builder interface - it'll be overridden after the user adjusts settings.
=> Lottie Player: Update Widget Description

widgets/image-grid/image-grid.php
This will prevent the loading tag from being set to `1` rather than `lazy`.
=> Image Grid: Fix Loading Attribute

compat/block-editor/widget-block.php
This PR will resolve the following notice:
`Warning: strpos(): Empty needle in /home/****/public_html/wp-content/plugins/so-widgets-bundle/compat/block-editor/widget-block.php on line 61`
This notice only occurs if there's a third party widget that doesn't have an author set.
=> Widgets Block: Ensure Widget Has Author

js/carousel.js
This PR will resolve a situation that can result in the previous navigation from working. It's not clear what specifically causes this situation but it potentially appears to be that there are more slides than the `Slides to Scroll` setting and that results in Slick rejecting the navigation attempt.
=> Anything Carousel: Account For Situation Where Prev Nav Won't Work

widgets/anything-carousel/styles/base.less
* Restored nav arrow margin.
* Reset top and bottom margin to zero to override possible theme styling.
=> Restore nav arrow margin

base/inc/routes/siteorigin-widgets-resource.class.php, base/siteorigin-widget.class.php, compat/block-editor/widget-block.js, compat/block-editor/widget-block.php
Resolves https://github.com/siteorigin/so-widgets-bundle/issues/1489
This PR adds Anchor support to the SiteOrigin Widgets Block. It does this by adding the `siteorigin_widgets_wrapper_id_BASE_ID` (replace `base_id` with the widget id) filter. (I'll add WB docs for that filter shortly)
Please note that a build will be required for this PR to work as expected.
=> Widgets Block: Add Anchor Support

compat/compat.php
This PR adds auto clearing cache support for:
- [LiteSpeed Cache](https://wordpress.org/plugins/litespeed-cache/)
For testing instructions, please refer to [the initial PR](https://github.com/siteorigin/so-widgets-bundle/pull/1258) for this functionality.
=> CSS Cache Compat: LiteSpeed Cache

widgets/google-map/google-map.php
This PR adds two new settings to the SiteOrigin Google Maps widget for the custom marker images. One for the global custom marker image size and one for custom markers.
=> Maps: Add Custom Marker Image Size Settings

widgets/contact/contact.php, widgets/contact/js/contact.js, widgets/contact/tpl/default.php
This PR adds [reCAPTCHA v3](https://www.google.com/recaptcha/admin) support to the contact form. 
Please test:
- upgrading an existing contact form with v2 enabled.
- v2.
- v3.
There's unfortunately no reliable way for us to detect the reCAPTCHA version type based on the provided key so if the user inputs an invalid one, there's not much we can do about it.
It might be a good idea to introduce a global setting to the Contact Form that allows for the reCAPTCHA to be loaded sitewide. This will allow for "improved verification" as reCAPTCHA will be able to monitor behaviour throughout the site.
=> Contact: reCAPTCHA v3

widgets/accordion/js/accordion.js
This will add a hyphen between the Anchor id and Panel Anchor.
=> Accordion: Add Hyphen prior to Panel Anchor

base/base.php
Resolve https://github.com/siteorigin/so-widgets-bundle/issues/1519
This PR:
- [Adds Times New Roman](https://github.com/siteorigin/so-widgets-bundle/commit/3121f828a573691c99fce823b318a5b1af8e3cea)
- [Alphabetise and Update Font Stacks](https://github.com/siteorigin/so-widgets-bundle/commit/2e9687535af0882bd3050dec2bbe17753e45ef50). The fontstack sourced from [CSS Font Stack](https://www.cssfontstack.com)
=> Web Safe Adjustments

base/inc/video.php
This PR accounts for a situation where the supplied video URL doesn't have the `v` parameter first and it also removes the URL rewrite to the embed URL as that's no longer needed (it appears it was removed shortly after implementation).
- Add a SiteOrign VIdeo Player widget and set it to use an **External VIdeo** and use: `https://www.youtube.com/watch?app=desktop&v=zlrb_X6fYZ0`
- Add a Video widget and add the above video also.
Confirm that the video widget works while the SiteOrigin Video Player widget doesn't. Switch to this PR branch and check if the Video Player widget is working as expected.
=> Standardize YouTube video URLs

widgets/hero/hero.php, widgets/hero/styles/default.less
This PR ensures that the top padding unit of measurement actually matters. Before this PR the Top and Bottom Padding and Extra Top Padding are simply added together and the unit of measurement isn't really factored in. After this PR the unit of measurement does matter.
To test:
- Add A Hero widget with a frame.
- Give the Hero some height (be it frame content or actual Height).
- Set Padding and Extra Top Padding using two different unit of measurements.
- Do the same for the Mobile version of those settings.
- Save and view the Hero.
- Inspect the Hero's `.sow-slider-image-wrapper` for the padding.
=> Hero: Better Top Padding Handling

js/slider/jquery.slider.js
This PR will help prevent a visual "jump" for sliders using the modern parallax. Prior to this PR, this jump is as a result of the image not parallaxing on load and that jump is the image correctly parallaxing.
To test this PR, please add a slider to the top of the page and to the second row. Add a slide or two and enable parallax for those slies. Save and view the page. If you see a jump shortly after load, try the PR. Otherwise, try simulating a slower connection to see if that allows you to replicate the jump.
=> Sliders: Wait for Modern Parallax to Be Setup

widgets/google-map/google-map.php
Resolve https://github.com/siteorigin/so-widgets-bundle/issues/1517
You can replicate this issue by:
- Set up a Static Google Map.
- Add some basic custom styling.
- View the map and then check the error log.
- Switch to this PR and confirm notice isn't occurring anymore.
=> Google Maps Static: Fix Custom Style Notice

base/inc/actions.php
Resolve https://github.com/siteorigin/so-widgets-bundle/issues/1528
`siteorigin_widgets_search_posts_order_by` will allow developers to alter the order by value to their desired usage.
Test snippet:
```
add_filter( 'siteorigin_widgets_search_posts_order_by', function( $order_by ) {
return 'post_modified ASC';
} );
```
=> Add `siteorigin_widgets_search_posts_order_by`

js/carousel.js
Resolve https://github.com/siteorigin/so-widgets-bundle/issues/1572
To test this issue install the Sydney theme. Set up a [test page](https://drive.google.com/uc?id=1e2faPhJVzCQV-wfNiipffZeqtuWXft7V) with this layout. Prior to this PR the number of visible slides will be reduced upon navigating to the next set of slides. After enabling this branch that won't happen. This issue is linked to Sydney but it could in theory happen with other themes.
=> Post Carousel: Prevent Partially Visible Scrolling From Affecting Anything Carousel

widgets/blog/blog.php
This will prevent a situation where the pagination can incorrectly render if the addon was previously active and it no longer is.
=> Blog: Prevent Potential Pagination Disaplay Issue After Disabling Addon

widgets/blog/styles/portfolio.less
Resolve https://github.com/siteorigin/so-widgets-bundle/issues/1582. This PR may help with the other sizing issue. I can't reliably replicate that - if it it doesn't, it should be resolved in a different PR so this part can be fixed.
A "column" width is required or the Portfolio JS will try to automatically size things into two columns.
=> Blog Portfolio: Resolve Column Sizing Issue

widgets/blog/blog.php
This PR will replicate how the sticky tag looks in Corp by adding the words Sticky to the post meta when a post is set to sticky.
=> Blog: Add Sticky Indicator to Meta

widgets/contact/contact.php, widgets/contact/fields/select.class.php
This PR will allow users to set the Select field to allow multiple selections. Selections will be listed in the email `with each, selected, item, separated, by a coma`.
=> Contact Select: Add `Allow multiple selections` Setting

js/sow.google-map.js
This PR prevents a situation where Google Maps Consent _may_ attempt to load the Google Maps API multiple times. To test this PR, test the standard consent prompt.
=> Google Maps Consent: Only Setup if Google Maps Not Already Setup

widgets/blog/styles/alternate.less
This PR will left align odd images in the Alternate Template. Currently, they're centered. It also cleans up the CSS for the featured image in this layout.
=> Blog Alternate: Left Align Odd Images

widgets/blog/css/style.less
This PR will ensure some of our adjustments using the article are more specific. This is important as it appears certain themes (such as Vantage) apply styles to the `article` element containing the post using `article.post`. In the case of Vantage, that results in unexpected padding while using the Alternate template.
=> Blog: More Specific Article Reset

widgets/blog/blog.php
This PR adds a filter that controls the trim indicator when the excerpt is generated. Filter example:
```
add_filter( 'siteorigin_widgets_blog_excerpt_trim', function( $trim ) {
return '[...]';
} );
```
You can also completely remove the excerpt (leaving only the continue reading link) using the following PHP:
```
add_filter( 'siteorigin_widgets_blog_excerpt_length', function( $length ) {
return 0;
} );
add_filter( 'siteorigin_widgets_blog_excerpt_trim', function( $trim ) {
return '';
} );
```
=> Blog: Add `siteorigin_widgets_blog_excerpt_trim`

widgets/blog/blog.php, widgets/blog/tpl/alternate.php, widgets/blog/tpl/grid.php, widgets/blog/tpl/masonry.php, widgets/blog/tpl/offset.php, widgets/blog/tpl/standard.php
This PR adds the `siteorigin_widgets_blog_image_sizes` filter, which is used to override the featured image size in certain templates. Currently, those templates are:
- Portfolio
- Grid
- Alternate
These sizes are based on an approximation of their Corp sizing. Users can override the image sizes using the `siteorigin_widgets_blog_image_sizes`. Users can also introduce new sizing for other templates using the same filter. For example, the following PHP will override the Offset featured image size to 123x321.
`add_filter( 'siteorigin_widgets_blog_image_sizes', function( $sizes ) {
$sizes['offset'] = array( 123, 321 );
return $sizes;
} );`
Users can also return an image size name instead of dimensions if preferred. For example, the following PHP will override the Grid Featured Image to …
=> Blog: Add `siteorigin_widgets_blog_image_sizes`

compat/compat.php
This PR will resolve the following warning if [LiteSpeed Cache](https://wordpress.org/plugins/litespeed-cache/) is active and headers have already been sent.
`Warning: Cannot modify header information – headers already sent by (output started at /home/**/public_html/wp-includes/functions.php:5275) in /home/**/public_html/wp-content/plugins/so-widgets-bundle/compat/compat.php on line 135`
=> LiteSpeed Cache Compat: Don't set Purge Header If Headers Already Sent

js/carousel.js
This is a follow-up for https://github.com/siteorigin/so-widgets-bundle/pull/1559 which will prevent it from affecting the Overlay theme for the same reason [it's not required for the Anything Carousel widget](https://github.com/siteorigin/so-widgets-bundle/pull/1573). 
[Test layout](https://drive.google.com/uc?id=1JdOiTWd7bvzyRWkZVem3j0TokEtSaLeI)
To test this confirm the base Post Carousel works as expecteg. Then try navigating to the next set of Post Carousel items for the Overlay theme - test using the arrow navigation rather than dots. You'll notice that the number of items is reduced - regardless of whether it makes sense. Switch to this branch and that won't happen anymore.
=> Post Carousel: Never Alter `SlidesToScroll` for `Overlay` Theme

widgets/image-grid/image-grid.php, widgets/image-grid/styles/default.less, widgets/image-grid/tpl/default.php
This PR introduces the Display Image Title setting which allows users to display the image's title directly above or below the image. It introduces two additional settings, the Image Title Position and Image Title Alignment settings.
While testing this PR please first create an image Grid with some images set with and without titles present. Once you've done that please then switch to this PR and ensure the image titles don't appear - they're enabled by default, but existing users shouldn't notice them for pre-existing Image Grids.
=> Image Grid: Add `Display Image Title` and Related Settings

widgets/editor/editor.php
This PR should resolve the following type of error:
`Fatal error: Uncaught ArgumentCountError: Too few arguments to function , 1 passed
/home/**/public_html/wp-content/plugins/so-widgets-bundle/widgets/editor/editor.php(98): apply_filters('widget_text', '<p>[jobs]</p>\n')`
I've submitted it to the users for confirmation.
To test this PR simply add any shortcode using the SiteOrigin Editor widget and confirm it works as expected.
=> Editor: Pass All Expected `widget_text` Arguments

base/inc/fields/number.class.php, base/inc/widgets/base-carousel.class.php
This PR resolves an issue that occurs if you set negative Slides to scroll or Slides to show value. Basically, the browser hangs. This PR ensures the values can only be positive. For example, `-2` is treated as `2`.
=> Carousel: Only Allow Positive Slides to scroll and Slides to show

widgets/contact/contact.php, widgets/contact/js/contact.js, widgets/contact/tpl/default.php
Resolve https://github.com/siteorigin/so-widgets-bundle/issues/1593
This PR implements two new anti-spam options the honeypot and a browser check. The browser check is stronger overall, but it requires JavaScript to be enabled so not all users will be okay with that.
To test the honeypot option: find the (CSS) hidden field in the markup and set it to show. Give it a value and submit it. If it failed after inputting data into the field, it worked.
To test the browser check, disable JavaScript.
=> Contact: Add `Honeypot` and `Browser Check` Anti-spam Options

widgets/contact/contact.php
This will only affect new instances of the widget.
To test this PR please add a Contact form to a page and then save. Switch to this branch and open the Contact form. Confirm that the Honeypot and Browser Check settings aren't enabled. Add a new instance of the contact form widget and then open it. Confirm those two settings are enabled.
=> Contact: Enable `Honeypot` and `Browser Check` by Default

widgets/blog/blog.php, widgets/blog/tpl/alternate.php, widgets/blog/tpl/grid.php, widgets/blog/tpl/masonry.php, widgets/blog/tpl/offset.php, widgets/blog/tpl/standard.php
This PR resolves an error that can occur when the Blog widget loads posts using Ajax.
`[22-Sep-2022 16:05:52 UTC] PHP Fatal error:  Uncaught Error: Using $this when not in object context in **\siteorigin\app\public\wp-content\plugins\so-widgets-bundle\widgets\blog\tpl\standard.php:2`
=> Blog: Resolve Error When Loading Posts Using Ajax

widgets/blog/styles/alternate.less, widgets/blog/styles/grid.less, widgets/blog/styles/masonry.less, widgets/blog/styles/offset.less, widgets/blog/styles/portfolio.less, widgets/blog/styles/standard.less
This will ensure LESS always trumps the base styles.
The removal of CSS in the alternate theme was intentional.
=> Blog: More Specific Template LESS Selectors

widgets/blog/blog.php
This PR prevents a situation where the URL for pagination links will be incorrect for the Blog widget when added using the SiteOrigin Widgets Block. This issue is detectable by navigating using the permalink and getting a 404. The URL will be: https://example.site/**wp-json/sowb/v1/widgets/previews/?**sow-1234=2
To test this PR you'll need to add a Blog widget using the SiteOrgin Widgets Block, and then save. View the page, and confirm the issue is present (doesn't always appear to happen). Switch to this branch, make a change to the block (required so it regenerates) and then save. View the page and it should work as expected. Edit the Blog widget and change the pagination to something other than the standard and confirm that also works.
=> Blog: Resolve Potential Incorrect URL When Added Using Widgets Block

base/base.php
This PR will allow users to replace Google Fonts with GDPR-friendly mirrors such as [Bunny Fonts](https://fonts.bunny.net/).
Test snippet:
```
add_filter( 'siteorigin_web_font_url ', function( $url ) {
return 'https://fonts.bunny.net/css';
} );
```
To test this snippet please add a SiteOrigin Headline widget, add some text and then set a font that's from Google Fonts.
=> Google Fonts GDPR: Add Support For `siteorigin_web_font_url `

compat/block-editor/widget-block.php
This PR will exclude the Blog Widget from the SO Widgets Block. This should help to prevent https://github.com/siteorigin/so-widgets-bundle/pull/1617 and ensure the widget is regenerated every load - which will prevent a situation where a post won't appear due to caching.
=> Widgets Block: Exclude Blog Widget

widgets/blog/blog.php
This PR resolves an issue that can occur for posts with non-Latin characters and without an excerpt.
To replicate this issue, please add some non-Latin characters to the top of a post. Please add enough words to exceed the standard read more (55). Create a page with a blog widget and then view the page. Does the Read More appear for the post with the Latin characters? If not, try switching to this branch.
=> Blog: Resolve Potential Missing Read More If Non-Latin Characters Present

widgets/contact/contact.php
This PR prevents the following notice:
`( ! ) Notice: Undefined index: _sow_form_id in C:\Users\alex\Local Sites\siteorigin\app\public\wp-content\plugins\so-widgets-bundle\widgets\contact\contact.php on line 1273`
This notice occurs if you add a contact form and then save the page without opening the contact. View the page and you'll get the above error message. Opening the widget will generate `_sow_form_id` and that's required to allow for multiple contact forms on the same page without submitting them all at once. We assume this exists because it almost always does outside of this one specific instance. This is more so to account for situations where I user adds a contact form and previews it prior to editing it - likely situation for that would be while using the Live Editor.
=> Contact: Prevent Notice Before Edit

widgets/post-carousel/styles/base.less
@AlexGStapleton This PR aims to resolve the potential situation where a theme has a rule in place, such as:
```
.site-content a { color: yellow; }
```
The above rule will beat the existing rule, which uses `inherit`. 
```
h3.sow-carousel-item-title a { color: inherit; }
```
=> Moved color to .sow-carousel-item-title link

base/inc/fields/tinymce.class.php
This PR will resolve an issue that can occur with PHP 8 if TInyMCE Plugins have been filtered and something other than array is returned.
`Fatal error: Uncaught TypeError: array_unique(): Argument #1 ($array) must be of type array, null given in /wp-content/plugins/so-widgets-bundle/base/inc/fields/tinymce.class.php:363`
=> TinyMCE Field: Prevent PHP 8 Uncaught TypeError TinyMCE Plugins

widgets/simple-masonry/simple-masonry.php
Resolve https://github.com/siteorigin/so-widgets-bundle/issues/1632. This PR removes any default set to `0`. No functionality difference is seen by doing this.
=> Simple Masonry: Remove Defaults Set to 0

js/carousel.js
This PR resolves an issue in the Block Editor if an Anything Carousel set to autoplay is present and the user tries to adjust a row/cell/widget color. 
[Test Layout](https://gist.githubusercontent.com/AlexGStapleton/b5a4dd547b7d8a5be5d139a9d85ad218/raw/b25b09d080fb47e4ec02930a0cd985dcd9b0d5a3/63659-test.html)
=> Carousel: Don't Autoplay in Block Editor Preview

js/lib/slick.js
This PR will resolve a display issue when adding Layout Builder items. To replicate it:
- Add an item that has a Layout Builder content type.
- Open it and add two Editor widgets. Apply 40px of margin to the first widget (or really, any Widget Style).
- Duplicate that item 6 times.
- Open the Carousel Settings and tick Loop Items.
When you scroll through the items. Item 5 & 6 will have the correct spacing while the cloned slides (the last two) won't.
=> Anything Carousel: Don't Clear Cloned IDs

base/inc/fields/html.class.php
To test this PR, add the following to any WB `form_options`:
```
'html' => array(
'type' => 'html',
'label' => __( 'HTML Example', 'so-widgets-bundle' ),
'markup' => '<p>This is an example. <hr> Another <em>example</em></p>', // Intentionally not using __.
),
```
=> `html` Form Field

widgets/blog/blog.php
Prior to this PR it wasn't possible to set the Excerpt Length to 0 without using a filter and even if you did, you would have to remove the Indicator using an additional filter. This PR allows Excerpt Length to be set to 0 and removes the Indicator.
=> Blog: Allow Excerpt Length to Be Set to 0, and Hide Indicator If It Is

widgets/simple-masonry/tpl/default.php
We don't want to lazy load these images. We want them to be loaded asap. One user reported an issue with the preloader never disappearing until scrolling all the way to the bottom of the widget (they had at least 40 to 50 images) but I haven't been able to replicate that on a test site (won't be replicable on a local install).
=> Masonry: If Preloader Is Active, Don't Add Loading Attr to Images

widgets/simple-masonry/js/simple-masonry.js, widgets/simple-masonry/styles/default.less
This PR moves away from using JavaScript to size the image dimensions and uses pure CSS instead. [object-fit](https://caniuse.com/#search=object-fit) is widely supported at this point with 98.63% global support so it's very safe to use. This change should reduce the potential for future CLS flagging due to measurement changes, make the widget lighter weight overall (fewer repaints), and it also resolves a sizing issue when titles are used.
=> Simple Image Masonry: Use Pure CSS (`object-fit`) for Sizing Images & Resolve Image Title Sizing Issue
